### ISSUE TITLE
Noobie Video Dash Question

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#1]
Also, I understand that you just created this 5 hours ago. I am guessing your not finished porting over the plugin?

https://github.com/heff/videojs-dashjs
https://github.com/Dash-Industry-Forum/dash.js/tree/development/contrib/videojs
https://github.com/videojs/video.js/wiki/Plugins

Is this going to replace your other thing?

**Comment by heff** [comment]
Yeah, this is being worked on and will eventually update the one in the dash.js contrib folder. heff/videojs-dashjs is old and should be deprecated.
