### ISSUE TITLE
Video not played until seeked to any point In safari

### ISSUE THREAD

**Issue by yogiswar1987** [videojs/videojs-contrib-dash#108]
Below is the dash log

[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Log] [4] [dash.js 2.2.0] MediaPlayer has been initialized  (dash.all.debug.js, line 2781)
[Log] [6] EME detected on this user agent! (ProtectionModel_01b)  (dash.all.debug.js, line 2781)
[Log] [7] Playback Initialized  (dash.all.debug.js, line 2781)
[Log] [0] EME detected on this user agent! (ProtectionModel_01b)  (dash.all.debug.js, line 2781)
[Log] [1] Playback Initialized  (dash.all.debug.js, line 2781)
[Log] [2] [dash.js 2.2.0] MediaPlayer has been initialized  (dash.all.debug.js, line 2781)
[Log] [2] Converted example-video_html5_api to dash.js player and added content: https://s3.amazonaws.com/_bc_dml/example-content/sintel_dash/sintel_vod.mpd  (dash.all.debug.js, line 2781)
[Log] [314] Parsing complete: ( xml2json: 1.89ms, objectiron: 1.31ms, total: 0.00320s)  (dash.all.debug.js, line 2781)
[Log] [315] Manifest has been refreshed at Tue Aug 30 2016 16:01:26 GMT+0530 (IST)[1472553086.416]   (dash.all.debug.js, line 2781)
[Log] [320] MediaSource attached to element.  Waiting on open...  (dash.all.debug.js, line 2781)
[Log] [267] Parsing complete: ( xml2json: 0.745ms, objectiron: 0.540ms, total: 0.00129s)  (dash.all.debug.js, line 2781)
[Log] [267] Manifest has been refreshed at Tue Aug 30 2016 16:01:26 GMT+0530 (IST)[1472553086.422]   (dash.all.debug.js, line 2781)
[Log] [268] MediaSource attached to element.  Waiting on open...  (dash.all.debug.js, line 2781)
[Log] [304] MediaSource is open!  (dash.all.debug.js, line 2781)
[Log] [304] Duration successfully set to: 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [306] Added 0 inline events  (dash.all.debug.js, line 2781)
[Log] [306] video codec: video/mp4;codecs="avc1.640028"  (dash.all.debug.js, line 2781)
[Log] [314] Schedule controller stopping for video  (dash.all.debug.js, line 2781)
[Log] [315] Start searching for initialization.  (dash.all.debug.js, line 2781)
[Log] [315] Perform init search: https://s3.amazonaws.com/_bc_dml/example-content/sintel_dash/sintel_video.mp4  (dash.all.debug.js, line 2781)
[Log] [316] Perform SIDX load: https://s3.amazonaws.com/_bc_dml/example-content/sintel_dash/sintel_video.mp4  (dash.all.debug.js, line 2781)
[Log] [316] audio codec: audio/mp4;codecs="mp4a.40.2"  (dash.all.debug.js, line 2781)
[Log] [317] Schedule controller stopping for audio  (dash.all.debug.js, line 2781)
[Log] [317] Start searching for initialization.  (dash.all.debug.js, line 2781)
[Log] [318] Perform init search: https://s3.amazonaws.com/_bc_dml/example-content/sintel_dash/sintel_audio.mp4  (dash.all.debug.js, line 2781)
[Log] [318] Perform SIDX load: https://s3.amazonaws.com/_bc_dml/example-content/sintel_dash/sintel_audio.mp4  (dash.all.debug.js, line 2781)
[Log] [318] No text data.  (dash.all.debug.js, line 2781)
[Log] [318] No fragmentedText data.  (dash.all.debug.js, line 2781)
[Log] [319] No embeddedText data.  (dash.all.debug.js, line 2781)
[Log] [319] No muxed data.  (dash.all.debug.js, line 2781)
[Log] [620] Parsing segments from SIDX.  (dash.all.debug.js, line 2781)
[Log] [623] Searching for initialization.  (dash.all.debug.js, line 2781)
[Log] [623] Found the initialization.  Range: 0-819  (dash.all.debug.js, line 2781)
[Log] [1394] Searching for initialization.  (dash.all.debug.js, line 2781)
[Log] [1394] Found the initialization.  Range: 0-748  (dash.all.debug.js, line 2781)
[Log] [1398] Parsing segments from SIDX.  (dash.all.debug.js, line 2781)
[Log] [1404] Start Event Controller  (dash.all.debug.js, line 2781)
[Log] [1405] Schedule controller starting for video  (dash.all.debug.js, line 2781)
[Log] [1406] Schedule controller starting for audio  (dash.all.debug.js, line 2781)
[Log] [1705] Initialization finished loading  (dash.all.debug.js, line 2781)
[Log] [1715] Getting the request for video time : 0  (dash.all.debug.js, line 2781)
[Log] [1715] SegmentBase: 0 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [1725] Initialization finished loading  (dash.all.debug.js, line 2781)
[Log] [1787] Native video element event: loadedmetadata  (dash.all.debug.js, line 2781)
[Log] [1787] Requesting seek to time: Infinity  (dash.all.debug.js, line 2781)
[Log] [1787] Starting playback at offset: Infinity  (dash.all.debug.js, line 2781)
[Log] [1734] Native video element event: loadedmetadata  (dash.all.debug.js, line 2781)
[Log] [1734] Getting the request for audio time : 0  (dash.all.debug.js, line 2781)
[Log] [1734] SegmentBase: 0 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [1792] Seeking to: 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [1739] Seeking to: 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [1801] Native video element event: ended  (dash.all.debug.js, line 2781)
[Log] [1747] Native video element event: ended  (dash.all.debug.js, line 2781)
[Log] [2074] Seeking to: 0  (dash.all.debug.js, line 2781)
[Log] [2020] Seeking to: 0  (dash.all.debug.js, line 2781)
[Log] [2080] Native video element event: play  (dash.all.debug.js, line 2781)
[Log] [2026] Native video element event: play  (dash.all.debug.js, line 2781)
[Log] [2027] SegmentBase: 0 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [2027] Getting the next request at index: 1  (dash.all.debug.js, line 2781)
[Log] [2027] SegmentBase: 14.041666666666666 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [2028] Schedule controller starting for video  (dash.all.debug.js, line 2781)
[Log] [2028] SegmentBase: 0 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [2029] Getting the next request at index: 1  (dash.all.debug.js, line 2781)
[Log] [2029] SegmentBase: 10.005333333333333 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [2029] Schedule controller starting for audio  (dash.all.debug.js, line 2781)
[Log] [3903] Got enough buffer to start.  (dash.all.debug.js, line 2781)
[Log] [3903] Buffered Range: 0 - 10.005334333333334  (dash.all.debug.js, line 2781)
[Log] [3905] Getting the request for audio time : 20.010666666666665  (dash.all.debug.js, line 2781)
[Log] [3905] Index for audio time 20.010666666666665 is 1  (dash.all.debug.js, line 2781)
[Log] [3905] SegmentBase: 10.005333333333333 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [3905] Getting the next request at index: 2  (dash.all.debug.js, line 2781)
[Log] [3905] SegmentBase: 20.010666666666665 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [3961] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [3907] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [4424] Buffered Range: 0 - 20.010667666666667  (dash.all.debug.js, line 2781)
[Log] [4794] Buffered Range: 0 - 30.016001  (dash.all.debug.js, line 2781)
[Log] [6393] Got enough buffer to start.  (dash.all.debug.js, line 2781)
[Log] [6394] Buffered Range: 0.08333333333333333 - 14.125001  (dash.all.debug.js, line 2781)
[Log] [6394] Requesting seek to time: 0.08333333333333333  (dash.all.debug.js, line 2781)
[Log] [6395] Getting the request for video time : 24.458333333333332  (dash.all.debug.js, line 2781)
[Log] [6395] Index for video time 24.458333333333332 is 1  (dash.all.debug.js, line 2781)
[Log] [6395] SegmentBase: 14.041666666666666 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [6395] Getting the next request at index: 2  (dash.all.debug.js, line 2781)
[Log] [6396] SegmentBase: 24.458333333333332 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [6450] Seeking to: 0.08333333333333333  (dash.all.debug.js, line 2781)
[Log] [6397] Seeking to: 0.08333333333333333  (dash.all.debug.js, line 2781)
[Log] [6555] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [6501] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [6557] Native video element event: playing  (dash.all.debug.js, line 2781)
[Log] [6503] Native video element event: playing  (dash.all.debug.js, line 2781)
[Log] [11650] Buffered Range: 0.08333333333333333 - 24.541667666666665  (dash.all.debug.js, line 2781)
[Log] [11654] Prior to making a request for time, NextFragmentRequestRule is aligning index handler's currentTime with bufferedRange.end. 0.08333333333333333  was changed to  24.541667666666665  (dash.all.debug.js, line 2781)
[Log] [11654] Getting the request for video time : 24.541667666666665  (dash.all.debug.js, line 2781)
[Log] [11654] Index for video time 24.541667666666665 is 1  (dash.all.debug.js, line 2781)
[Log] [11654] SegmentBase: 14.041666666666666 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [11654] Getting the next request at index: 2  (dash.all.debug.js, line 2781)
[Log] [11655] SegmentBase: 24.458333333333332 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [19018] Buffered Range: 0.08333333333333333 - 41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [19018] Prior to making a request for time, NextFragmentRequestRule is aligning index handler's currentTime with bufferedRange.end. 41.70833333333333  was changed to  41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [19018] Getting the request for video time : 41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [19019] Index for video time 41.79166766666667 is 2  (dash.all.debug.js, line 2781)
[Log] [19019] SegmentBase: 24.458333333333332 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [19019] Getting the next request at index: 3  (dash.all.debug.js, line 2781)
[Log] [19019] SegmentBase: 41.708333333333336 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [19038] Prior to making a request for time, NextFragmentRequestRule is aligning index handler's currentTime with bufferedRange.end. 0.08333333333333333  was changed to  30.016001  (dash.all.debug.js, line 2781)
[Log] [19038] Getting the request for audio time : 30.016001  (dash.all.debug.js, line 2781)
[Log] [19038] Index for audio time 30.016001 is 2  (dash.all.debug.js, line 2781)
[Log] [19039] SegmentBase: 20.010666666666665 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [19039] Getting the next request at index: 3  (dash.all.debug.js, line 2781)
[Log] [19039] SegmentBase: 30.016 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [22766] Buffered Range: 0 - 40.021334333333336  (dash.all.debug.js, line 2781)
[Log] [22767] Prior to making a request for time, NextFragmentRequestRule is aligning index handler's currentTime with bufferedRange.end. 40.02133333333333  was changed to  40.021334333333336  (dash.all.debug.js, line 2781)
[Log] [22767] Getting the request for audio time : 40.021334333333336  (dash.all.debug.js, line 2781)
[Log] [22767] Index for audio time 40.021334333333336 is 3  (dash.all.debug.js, line 2781)
[Log] [22768] SegmentBase: 30.016 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [22768] Getting the next request at index: 4  (dash.all.debug.js, line 2781)
[Log] [22768] SegmentBase: 40.02133333333333 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [23667] Buffered Range: 0 - 50.02666766666667  (dash.all.debug.js, line 2781)
[Log] [26638] Buffered Range: 0.08333333333333333 - 41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [26638] Getting the request for video time : 52.375  (dash.all.debug.js, line 2781)
[Log] [26638] Index for video time 52.375 is 3  (dash.all.debug.js, line 2781)
[Log] [26638] SegmentBase: 41.708333333333336 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [26639] Getting the next request at index: 4  (dash.all.debug.js, line 2781)
[Log] [26639] SegmentBase: 52.375 / 888.0640258789062  (dash.all.debug.js, line 2781)
[Log] [36619] Native video element event: pause  (dash.all.debug.js, line 2781)
[Log] [36566] Native video element event: pause  (dash.all.debug.js, line 2781)
[Log] [36625] Seeking to: 8.518599768622602  (dash.all.debug.js, line 2781)
[Log] [36571] Seeking to: 8.518599768622602  (dash.all.debug.js, line 2781)
[Log] [36823] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [36770] Native video element event: seeked  (dash.all.debug.js, line 2781)
[Log] [36824] Native video element event: play  (dash.all.debug.js, line 2781)
[Log] [36770] Native video element event: play  (dash.all.debug.js, line 2781)
[Log] [36771] Prior to making a request for time, NextFragmentRequestRule is aligning index handler's currentTime with bufferedRange.end. 8.518599768622602  was changed to  41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [36771] Getting the request for video time : 41.79166766666667  (dash.all.debug.js, line 2781)
[Log] [36771] Index for video time 41.79166766666667 is 2  (dash.all.debug.js, line 2781)

**Comment by forbesjo** [comment]
This source has a problem in the [dash.js demo player](http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html) as well. Some of the other sample sources seem to play fine.

This needs investigation in dash.js

**Comment by forbesjo** [comment]
Closing because this is a problem in dash.js
