### ISSUE TITLE
Stream stops after 35 seconds no error

### ISSUE THREAD

**Issue by ColonelMillerSG21** [videojs/videojs-contrib-dash#109]
Hey guys :)

I'm testing video.js with dash.js and your plugin together on my testpage but after 35 seconds it stops each time. When i keep the dev tools open in chrome it pauses (see screenshot), but if i close the dev tools it plays the stream (for 35 seconds).
Once it starts the timeline shows random numbers as you can see in the screenshot and before the stream starts playing i also get this error which doesn't stop it from playing those 35 seconds: 

dash.all.min.js:9 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.

After 35 seconds you will notice that it starts circling for 1 second and then freezes. I'm using a Wowza streaming server version 4.1. This is the testpage: http://rp-productions.net/test/

![capture](https://cloud.githubusercontent.com/assets/11478472/18128123/8fecbae2-6f84-11e6-8bcc-055e42d91e14.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11478472/18128504/6038aec6-6f86-11e6-9301-a58f6f85594a.PNG)

**Comment by forbesjo** [comment]
Does your source play in the dash.js reference player http://dashif.org/reference/players/javascript/v2.2.0/samples/dash-if-reference-player/index.html ?

**Comment by ColonelMillerSG21** [comment]
Yes and i resolved this, well not entirely but it is palying now longer then 35 seconds. Only issue i still ahve is that i don't get the time, i just get those random numbers like in the screenshot. Everything is fine in the dash reference player though

**Comment by BrandonOCasey** [comment]
what was the resolution? It may help others in the future

**Comment by ColonelMillerSG21** [comment]
The js files where at the bottom instead of the header that caused it. Idk i still think that shouldn't happen but for some reason it requires to load the files all in the header section or this will happen. Only issue i have left is the timecode :(

**Comment by forbesjo** [comment]
The live display is fixed by https://github.com/videojs/videojs-contrib-dash/pull/130, which is now part of 2.6.1.
Closing this issue
