### ISSUE TITLE
Dash 1.5 integration

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#11]
Dashjs is currently at 1.4 and has refactored https://github.com/Dash-Industry-Forum/dash.js/pull/676 for development.

I tried to upgrade to use the latest version of dashjs#development (1.5) which includes PR #676, but it looks there is breaking changes with videojs-contrib-dash integration.

https://github.com/Dash-Industry-Forum/dash.js/issues/664

https://groups.google.com/forum/#!topic/dashjs/jQ0B5Q-xOlw

I am guessing this is known? Or is there a planned feature branch for migration?

I'll dig deeper into it next week to figure why playback is breaking (Currently video stalls at the end of the video as soon as you press play).

**Comment by imbcmdth** [comment]
@chemoish Thanks for letting us know of some important changes that are coming up. If you find anything that can be improved, please let us know or feel free to submit a PR.

**Comment by chemoish** [comment]
Still trying to wrap my head around videojs > tech > source handlers currently (For another issue). Will do once I get more familiar with the codebase.

**Comment by chemoish** [comment]
Dash#1.5 works for me.
