### ISSUE TITLE
Extend dash with custom XHRLoader

### ISSUE THREAD

**Issue by silverbucket** [videojs/videojs-contrib-dash#118]
I'd like to implement my own segment fetching function, with DASH I can do this using the `.extend` function on the initialized dash instance:

```javascript
player = dashjs.MediaPlayer().create();
player.extend("XHRLoader", customMediaRequest, false);
```

However I can't figure out how to do this the right way with the videojs-contrib-dash module, any pointers? Is it even possible?

**Comment by forbesjo** [comment]
You can do this by setting your options in `beforeInitialize`:
```
videojs.Html5DashJS.beforeInitialize = function(player, mediaPlayer) {
  mediaPlayer.extend('XHRLoader', customMediaRequest, false);
};

var vjsPlayer = videojs('videoId');
vjsPlayer.src(source);
```

**Comment by silverbucket** [comment]
Hi @forbesjo I tried this and it didn't seem to work. 

```javascript:
      videojs.beforeInitialize = function (player, mediaPlayer) {
        mediaPlayer.extend('XHRLoader', function (){console.log('TEST');}, false);
      };

      var player = videojs('video');
      player.ready(function () {
        player.src({
          src: "http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd",
          type: 'application/dash+xml'
        });
        player.play();
      });
```

`TEST` is never displayed, and the media fetching happens without any issue.

**Comment by silverbucket** [comment]
ping @forbesjo

**Comment by forbesjo** [comment]
`videojs.Html5DashJS.beforeInitialize` needs to be set, in your code sample you have `videojs.beforeInitialize`

**Comment by silverbucket** [comment]
@forbesjo - thanks for the reply. I forgot to explain that. On the `videojs` object there is a function `beforeInitialize` however on the `videojs.Html5DashJS` object that function does not exist. So I thought perhaps it was a typo. Any ideas?

**Comment by forbesjo** [comment]
That function doesn't exist by default which is why you don't see it.

**Comment by silverbucket** [comment]
@forbesjo of course! sorry, I get it now and it works fine :)

**Comment by subhranshudas** [comment]
Do you guys know if dash.js or videojs has any facility to extend the XHR request it makes in `ProtectionController.js` i mean if i want to add something in the request body? can we use player.extend() in any sense?
