### ISSUE TITLE
Default subtitles and PlayBackrates  ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/videojs-contrib-dash#126]
playbackrates doesn't  work if it  
data-setup="{ &quot;html5&quot;: { &quot;nativeTextTracks&quot;: false },&quot;playbackRates&quot; : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}">
and  how to make the running any default subtitles?  is it possible?

**Comment by forbesjo** [comment]
There is now caption support in 2.9.0 of this plugin. `playbackRates` also works, I think your quoting is off. See http://jsbin.com/nisadob/edit?html,output
