### ISSUE TITLE
Live stream freezes after a few seconds

### ISSUE THREAD

**Issue by tedtucker** [videojs/videojs-contrib-dash#129]
Here is my example using videojs-contrib-dash - v2.6.0 - 2016-12-12:
http://codepen.io/terrafox/pen/a7b707e8ac08255b29beb282562b4963

The LIVE stream freezes after about 30 seconds.

Using the DASH reference player 2.3.0,  it works no problem.. for hours.
http://codepen.io/terrafox/pen/47a780d3698f49fc304a07d9d11c276d

**Comment by tedtucker** [comment]
Seems this is the same issue:

#https://github.com/videojs/videojs-contrib-dash/issues/81
#https://github.com/videojs/videojs-contrib-dash/issues/109
#https://github.com/videojs/videojs-contrib-dash/issues/35

**Comment by todojs** [comment]
We have the same issue. After few second the Live Dash are stoped and the console show:

`
dash.all.min.js:3 [63936] ThroughputRule requesting switch to index:  0 type:  audio Average throughput 591248 kbps 
dash.all.min.js:3 [63937] AbrController (audio) stay on 0/0 (buffer: 2.818) 
dash.all.min.js:3 [63938] Getting the request for audio time : 20433.455022222224 
dash.all.min.js:3 [63939] Index for audio time 20433.455022222224 is 299 
dash.all.min.js:3 [63939] SegmentTimeline: 20427.41768888889 / 9999999999 
dash.all.min.js:3 [63939] Getting the next request at index: 300 
dash.all.min.js:3 [64081] AbrController (video) stay on 0/3 (buffer: 0.106) 
dash.all.min.js:3 [64082] Getting the request for video time : 20430.74302222222 
dash.all.min.js:3 [64082] Index for video time 20430.74302222222 is 180 
dash.all.min.js:3 [64082] SegmentTimeline: 20420.74302222222 / 9999999999 
dash.all.min.js:3 [64082] Getting the next request at index: 181 
dash.all.min.js:3 [64440] ThroughputRule requesting switch to index:  0 type:  audio Average throughput 591248 kbps 
dash.all.min.js:3 [64440] AbrController (audio) stay on 0/0 (buffer: 2.818) 
dash.all.min.js:3 [64440] Getting the request for audio time : 20433.455022222224 
dash.all.min.js:3 [64441] Index for audio time 20433.455022222224 is 299 
dash.all.min.js:3 [64441] SegmentTimeline: 20427.41768888889 / 9999999999 
dash.all.min.js:3 [64441] Getting the next request at index: 300 
dash.all.min.js:3 [64584] Switch to index 0; buffer is empty. 
dash.all.min.js:3 [64584] Switch history rule index: 0 samples: 8 drops: 1 
dash.all.min.js:3 [64584] AbrController (video) stay on 0/3 (buffer: 0.106) 
dash.all.min.js:3 [64584] Getting the request for video time : 20430.74302222222 
dash.all.min.js:3 [64585] Index for video time 20430.74302222222 is 180 
dash.all.min.js:3 [64585] SegmentTimeline: 20420.74302222222 / 9999999999 
`
etc...

**Comment by helenjer** [comment]
The same behaviour - with live DASH Widevine if autoplay used.
Issue doesn't reproduce by us on dash.js, on videojs-contrib-hls without autoplay, on VOD, or on non-encrypted live video.

**Comment by albertoronu** [comment]
I'm having the same issue. Trying to workaround using stalled or waiting events, by reseting the player and reloading the source.

videojsPlayer.on('waiting', function(e) {
           videojsPlayer.pause();
           videojsPlayer.reset();
            videojsPlayer.src(this.videojsPlayer.currentSource()); 
});

Problem is that both stalled and waiting are called randomly, not only when player freezes.

**Comment by squarebracket** [comment]
Do you have an example feed?
