### ISSUE TITLE
VideoJS 5.0 integration

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#13]
I also noticed that they are moving away from closure?

At least, https://github.com/videojs/video.js/blob/v4.12.13/src/js/exports.js doesn't exist in 5.0.

videojs.Html5 no longer exists and chokes on load.

![screen shot 2015-08-11 at 11 49 15 am](https://cloud.githubusercontent.com/assets/549319/9206847/0fe6da20-401f-11e5-9562-0041ae39deb8.png)

---

My issues are kind of all over the place as I am trying to figure out how to reload a src with protection data (`videojs('player').src({...})`). As it doesn't seem like there is any mechanism to do so.

From `player > tech > source handler`.

I will continue my efforts using 4.12 for now I suppose.

#grumblecakes

**Comment by gkatsev** [comment]
Yep, 5.x has a lot of changes. The Dash tech is currently developed against vjs 4.x. See https://github.com/videojs/video.js/wiki/5.0-Change-Details for the changes happening between vjs 4.x and 5.x.

**Comment by chemoish** [comment]
Leveraging 4.x for now. Will open a different issue if there are 5.0 issues when released.
