### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by odiszapc** [videojs/videojs-contrib-dash#136]
Excuse me, is it working on iOS Safari (iPhone/iPad) ?

Thanks!

**Comment by forbesjo** [comment]
Dash.js (the library this plugin adapts) only works on MSE supported browsers (http://caniuse.com/#feat=mediasource), iOS is not supported

**Comment by vsalema** [comment]
the videojs dash player works very well in all browsers
see the demo
https://filmsgratos.site/suplayernuevo2.html

**Comment by vsalema** [comment]
solution
https://codepen.io/vsalema/pen/xxJxWxQ
