### ISSUE TITLE
Contrib-dash not working in Microsoft Edge

### ISSUE THREAD

**Issue by Tralapo** [videojs/videojs-contrib-dash#14]
VideoJS-contrib-dash does not seem to work in Microsoft's new browser Edge. The browser does support Dash, because a stand-alone dash.js player does work in the browser.

When using it with VideoJS through contrib-dash, the player fails. No usefull console-output, just the basic error.

```
"The video could not be loaded, either because the server or network failed or because the format is not supported."
```

**Comment by patrickkettner** [comment]
@Tralapo can you provide an example of the issue? I tried [demo](http://videojs.github.io/videojs-contrib-dash/) in Edge and it worked properly

**Comment by Tralapo** [comment]
@patrickkettner You'r re right, that demo does work in Edge. I created two demo's for you:

1) videojs-contrib-dash: Does not work in Edge for me: http://bit.ly/1HLd1Q7

2) dash.js only: does work in Edge for me: http://bit.ly/1KlphIT

**Comment by Tralapo** [comment]
@patrickkettner @forbesjo Where you able to take a look at the demo's I created?

**Comment by forbesjo** [comment]
@Tralapo your video does work if I load it into your player with `src()`. I haven't yet looked into why the error is occurring but that can be a possible workaround.

**Comment by Tralapo** [comment]
@forbesjo How would that work? Can't seem to find the right way of doing so in the docs. And does that work when having >5 players on one page?

Problem would also be solved if we could find a solution for #10 by the way.

**Comment by forbesjo** [comment]
@imbcmdth and I discovered that Edge has native Dash support which causes video.js to use the native source handler and not the Dash source handler registered by this plugin. In my previous comment I set the player source with
```
videojs.players.CamTest.src('https://stream.bobkoetsier.nl/live/havenkom.stream/manifest_mvtime.mpd')
```
The native source handler cannot handle that type of source input so the player then uses the Dash source handler.

**Comment by Tralapo** [comment]
@forbesjo I don't know what I do wrong, but if I apply that code the player won't load at all.

**Comment by forbesjo** [comment]
Here is a jsbin of what I'm doing http://jsbin.com/tewinevahe/1/edit?html,output

**Comment by Tralapo** [comment]
@forbesjo Thanks, that one works indeed. But as soon as I add multiple sources, it fails again.

I need three sources, because I want the stream to be supported on all platforms and browsers. On Android I need HLS, because at least my devices do not seem to play dash. Firefox won't play HLS and/or Dash, so that one needs RTMP with Flash.

It works in Edge if I put HLS first and Dash second, but that brings me back to my problem in #10, so that's not ideal either. If you put Dash first and HLS second, Edge goes bad.

```
player.ready(function() {
	player.src([
  { type: "application/dash+xml", src: "https://stream.bobkoetsier.nl/live/havenkom.stream/manifest_mvtime.mpd" },
  { type: "application/x-mpegurl", src: "https://stream.bobkoetsier.nl/live/havenkom.stream/playlist.m3u8" },
  { type: "rtmp/mp4", src: "rtmps://stream.bobkoetsier.nl/live/havenkom.stream" }
]);
});
```

**Comment by forbesjo** [comment]
The array of sources doesn't all need to be the same type, see this example http://jsbin.com/noxanerewu/edit?html,output

**Comment by Tralapo** [comment]
@forbesjo That solution doesn't work. Dash won't be selected at all. Edge chooses HLS and Chrome falls back to RTMP with Flash. I would like to move away from Flash, the reason I look at Dash.

**Comment by imbcmdth** [comment]
@Tralapo I have a simple change that should give videojs-contrib-dash priority over any native support in #16 

Should be landing in master soon. It would be great if you could test it and make sure it fixes the issue you are seeing.

**Comment by Tralapo** [comment]
@imbcmdth Works, thanks!
