### ISSUE TITLE
endless loading

### ISSUE THREAD

**Issue by jimmywarting** [videojs/videojs-contrib-dash#140]
live stream don't play
it's working at [dashif.org](http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html?url=https://svt10-a.akamaized.net/u/svt10.mpd)

**Comment by forbesjo** [comment]
Do you have a sample source to debug this issue?

**Comment by jimmywarting** [comment]
1) Go to http://videojs.github.io/videojs-contrib-dash/
2) open console
3) enter:
```js
player.src({src: 'https://svt10-a.akamaized.net/u/svt10.mpd', type: 'application/x-mpegurl'})
```

**Comment by forbesjo** [comment]
Sorry for not getting to this earlier but it looks like your source is be down, if this is still an issue could you post an updated source

**Comment by jimmywarting** [comment]
It's still valid, i just pasted it in here: http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/#https://svt10-a.akamaized.net/u/svt10.mpd

Works just fine
