### ISSUE TITLE
Any event similar to beforeRequest same as HLS

### ISSUE THREAD

**Issue by pratik2pris** [videojs/videojs-contrib-dash#160]
Hello

I have DASH files at AWS s3 and all files are private. So I want to generate signed url before it goes to Player. I can do this for HLS via beforeRequest method. But in videojs-contrib-dash I am not able to find such a event.

So result is the videos in packages will not load in player.

Any help will be appreciate.

**Comment by khavishbhundoo** [comment]
@pratik2pris  did you found a solution ?

**Comment by gkatsev** [comment]
contrib-dash includes dash.js, you'll want to look at dash.js documentation for these features. If you're using VHS in video.js (built-in by default) beforeRequest will work for those requests as well (even if the the documentation says to use player.hls, it applies to dash as well).
