### ISSUE TITLE
Where is mediaPlayer in VJS6

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#177]
Hi

Just trying VJS6 for the first time, and using contrib-dash 2.8.2.

With contrib-dash on VJS5, to access the mediaPlayer after VJS Setup we currently use:-
this.tech_.sourceHandler_.mediaPlayer_

But this is now not working with VJS6. Any ideas how/where to access this subsequently now please?

We use this to alter dash options upon entering Fullscreen etc...

**Comment by richardbushell** [comment]
Ah, looks like VJS6 may have made _tech asynchronous, so I may have been trying to access this too early. Looking into this now...

**Comment by forbesjo** [comment]
You should be able to access the dash.js mediaPlayer with `player.dash.mediaPlayer` which should be available once the source is loaded.

**Comment by gkatsev** [comment]
In 6.x, source loading is asynchronous (this is actually in-line with the spec), so, `player.ready()` is recommended.

**Comment by richardbushell** [comment]
Thanks Jo, yes I'd tried that too, but was getting the same problem. Now, both routes to the MediaPlayer object work fine, I just had to delay the access to fall in line with async...

**Comment by richardbushell** [comment]
@gkatsev, I was already trying to access this within the Callback function of VJS Setup, so what's the best way of ensuring it's available by using player.ready()? I was using either:-
this.tech_.sourceHandler_.mediaPlayer
or
this.dash.mediaPlayer
BUT how do I KNOW when it's ready and then access it at that time in code?

**Comment by gkatsev** [comment]
I'm not certain how this source handler works, but I would assume it should be available inside the player.ready handler.

**Comment by richardbushell** [comment]
But isn't the VJS Setup Callback function only executed when VJS has setup and is ready? Sorry if I'm being dim...

**Comment by richardbushell** [comment]
Sorry, just re-looked at my setup, and of course I'm then manually adding a SRC inside the callback.
@forbesjo - so how then do I code for knowing that has been setup before accessing the dash object?

**Comment by gkatsev** [comment]
If the player is already ready, it'll call the callback immediately rather than wait for it to be ready.

**Comment by forbesjo** [comment]
@richardbushell are you still having issues after wrapping your code in `ready()`?

**Comment by richardbushell** [comment]
Sorry, how do I wrap the async SRC load response in ready() ???
Here is my pseudo-code:-
var player = videojs('video', videoSetup, function () {
	this.src([ { ... } , { ... } ]);
	var theMediaPlayer = this.dash.mediaPlayer;   // example only: how to know this is ready/defined?
I would be hugely grateful if you could advise on the actual code to wrap this in ready() please.

**Comment by forbesjo** [comment]
Oh I think @gkatsev's comment is for when you're loading a source via a source element or as a data-setup/videojs constructor setting. If you're loading the source later you can wait for `loadstart`.

See https://jsbin.com/rigoratura/edit?html,js,console,output

**Comment by richardbushell** [comment]
Thanks @forbesjo 
In the jsbin example, is there any reason not to include the loadstart listener inside the callback function? And wouldn't it be better to set the listener before the source is added, just in case loadstart is fired immediately before the listener was set (if that's even possible)? For example, is this OK?:-
var player = videojs('video', videoSetup, function () {
this.on('loadstart', function() { ... })
this.src([ { ... } , { ... } ]);
})

**Comment by forbesjo** [comment]
Yes you would want to set the listener before setting the source

**Comment by richardbushell** [comment]
Thanks for confirming @forbesjo
@gkatsev Please can you confirm that you agree that the above code is now optimal, and that there is nothing that Jo or myself are missing with regard to your suggestion for using player.ready() for async handling of a dynamically loaded source.

**Comment by richardbushell** [comment]
@gkatsev Just to clarify, as this is a bit disjointed, my TWO questions are these...

Under VJS6 the sources are now loaded async, so:-

Q1) if we include "sources" within the VJS Setup Object does the Callback function only get called AFTER the SRC is "ready", so that dash object would be immediately available?

Q2) if we don't pass in any "sources" in the VJS Setup Object, but only add them to the player dynamically WITHIN the Callback function, then Jo's suggestion to use 'loadstart' is the only/optimal way to guarantee they're "ready" and accessible?

**Comment by gkatsev** [comment]
> Q1) if we include "sources" within the VJS Setup Object does the Callback function only get called AFTER the SRC is "ready", so that dash object would be immediately available?

Yes, I believe when `ready` is called, the dash player will be available.

> Q2) if we don't pass in any "sources" in the VJS Setup Object, but only add them to the player dynamically WITHIN the Callback function, then Jo's suggestion to use 'loadstart' is the only/optimal way to guarantee they're "ready" and accessible?

Yes, if you want to know that the video has loaded and the dash player is available, `loadstart` is the way to do. In fact, you should be able to use `loadstart` for both scenarios.

**Comment by richardbushell** [comment]
Perfect, thank you both, VJS6 async sources now working fine with both methods...
