### ISSUE TITLE
Dash Playback Issue when embedded in Angular2 Application

### ISSUE THREAD

**Issue by jgainfort** [videojs/videojs-contrib-dash#18]
I know Angular2 is in alpha but I still thought I would bring this to your attention.

I am currently messing around with an Angular2 wrapper around videojs and when I try to incorporate dash into the player I am getting the following error in the console.

Parsing complete: ( xml2json: 4ms, objectiron: 4ms, total: 0.008s) 
dash.all.js:9 Playback initiated! 
dash.all.js:9 Manifest has been refreshed. 
dash.all.js:9 Manifest has loaded. 

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.

Now if I take the video tag with the same exact properties outside of the Angular2 wrapper everything works as expected.

A couple of points: 
- I have verified that the video tag has a unique ID.
- I am testing the application in Chrome Version 47.0.2496.0 canary (64-bit)
- I am able to use the HLS plugin in this same wrapper and everything works perfectly.
- For some reason (maybe another issue should be raised) if trying to play HLS and DASH in two separate players on the same page, the HLS player will fail.

Stepping through the workflow I cant seem to find when or where the error occurs.

I can provide the setup and code necessary to replicate if its desired.

**Comment by forbesjo** [comment]
Is this still an issue and if so could you post a reduced test case? Thanks
