### ISSUE TITLE
Too frequent stream quality switching from SD to HD dynamically.

### ISSUE THREAD

**Issue by mjneil** [videojs/videojs-contrib-dash#186]
@rishigohil commented on [Mon May 22 2017](https://github.com/videojs/videojs-contrib-hls/issues/1127)

## Description
The original recordings are in WEBM container (VP9 video Codec and AAC audio Codec). The issue we are facing is our streams are bouncing back and forth between HD and SD without any network fluctuations.

![image](https://cloud.githubusercontent.com/assets/5967748/26323531/33a9f76a-3efd-11e7-8a55-52458d9c4632.png)

Is there any way I can fix this or can log when the player changes the source quality?

---

@gesinger commented on [Mon May 22 2017](https://github.com/videojs/videojs-contrib-hls/issues/1127#issuecomment-303245109)

Hey @rishigohil , how are you playing the webm files? Would you be able to put together a reduced test case using our [starter template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.

---

@rishigohil commented on [Tue May 23 2017](https://github.com/videojs/videojs-contrib-hls/issues/1127#issuecomment-303475328)

http://jsbin.com/zidelo/edit?html,js,output

Here you go. You can also check here. 

https://cobweb1.fau.edu/Demos/VideoJs.html

---

@rishigohil commented on [Wed May 24 2017](https://github.com/videojs/videojs-contrib-hls/issues/1127#issuecomment-303704529)

@gesinger Any luck?

**Comment by arpu** [comment]
http://dashif.org/reference/players/javascript/v2.5.0/samples/dash-if-reference-player/index.html?url=https://cobweb1.fau.edu/LCVS/QMB3600-201701-003/Videos/ITGROUP_Testing_05_23_2017_1HD/VP9/manifest.mpd

looks like same problem with upstream dash component

**Comment by rishigohil** [comment]
Oh, that's interesting. So it means the player is not the issue?

**Comment by mjneil** [comment]
That means it is probably an issue with Dash.js or the content itself. `videojs-contrib-dash` just does the videojs integration. All the work for loading segments and selecting quality is done within Dash.js. I'd suggest opening an issue in the Dash.js project

**Comment by rishigohil** [comment]
Ah okay. I'll reference this issue in their repo.
