### ISSUE TITLE
max buffer time

### ISSUE THREAD

**Issue by taliptako** [videojs/videojs-contrib-dash#189]
Hello,
I'm using this plugin for my dash videos you can check from this url: https://detayhosting.com/player4/
But its buffering all the video i wanna set limit for this like only buffer 5 second can i do this ?

**Comment by forbesjo** [comment]
You can use an initialization hook (https://github.com/videojs/videojs-contrib-dash#initialization-hook) to set dash.js's forward buffer http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html
