### ISSUE TITLE
Questions work with dashjs: player.setQualityFor("video",240);

### ISSUE THREAD

**Issue by Yalhu** [videojs/videojs-contrib-dash#201]
#### Player "example-video" is already initialised. Options will not be applied.
```javacsript
var player=videojs('example-video',{})
player.src({
        src: 'dash.mpd',
        type: 'application/dash+xml'
});
$(btn240).click(function(){
   player=videojs('example-video', {
        html5: {
            dash: {
                setAutoSwitchQuality:false,
                setQualityFor:["video",240]
           }
       }
   })
});
```

**Comment by forbesjo** [comment]
You should be able to call `player.dash.mediaPlayer.setQualityFor('video', 240)` in your button handler.

**Comment by Yalhu** [comment]
@forbesjo `  player.dash.mediaPlayer.setQualityFor('video',2)` can be call.  But it dose not work well, the quality doesn't change. When i call `player.dash.mediaPlayer.getQualityFor('video')` ,the result is always 0 thought i call `setAutoSwitchQuality:false,`.
(i don't really understand what means of the second arguments 'number')
