### ISSUE TITLE
Cannot read property 'mediaPlayer' of undefined

### ISSUE THREAD

**Issue by Yalhu** [videojs/videojs-contrib-dash#205]
i want to get the video quality when it is ok, but there is an error: Cannot read property 'mediaPlayer' of undefined
``` javascript 
videojs.hook('setup', function(player){
    player.dash.mediaPlayer.getQualityFor('video')
});
var player = videojs('example-video', {
        html5: {
            nativeCaptions: false,
            dash: {
                setLimitBitrateByPortal: true,
                setMaxAllowedBitrateFor: ['video', 2000],
            }
        }
    });
```
i think it's the issue #24( Using dash.js APIs in combination with video.js APIs when using videojs-contrib-dash).
And i still don't know what should i do  on my case. Is there anyone give me some example or code comfortably ?

**Comment by mjneil** [comment]
Try using the `videojs.Html5DashJS.hook('beforeinitialize', callback)` https://github.com/videojs/videojs-contrib-dash#initialization-hook

**Comment by Yalhu** [comment]
@mjneil  There is a new error:"Uncaught: You must first call play() to init playback before calling this method" weather i call `myplayer.play()`.
``` javascript
var myCustomCallback = function(myplayer, mediaPlayer) {
//myplayer.play();
myplayer.dash.mediaPlayer.getQualityFor('video');//error
mediaPlayer.getQualityFor('video');//error
};
videojs.Html5DashJS.hook('beforeinitialize', myCustomCallback);
```

**Comment by Yalhu** [comment]
Now i have this error:Failed to set the 'duration' property on 'MediaSource': The MediaSource's readyState is not 'open'. Dash-Industry-Forum/dash.js#1349
I've use the latest version: videojs 6.2.1, vjs-dash 2.9.1, dashjs 2.6.0.
Is there any other state i can try out?(hook initialize is still not work).
Is state of beforeinitialize belong to vjs-dash or dashjs??
I think hook beforeinitialize have some problem. when i throttl web to slow 3G, it seems no error. 
Or is this still a dashjs problem of initialize?
```
       var myCustomCallback = function(player, mediaPlayer) {
            mediaPlayer.on('qualityChangeRendered',function(){
               var i=player.dash.mediaPlayer.getQualityFor('video');
               ..
            });
        };
        videojs.Html5DashJS.hook('beforeinitialize', myCustomCallback);
```

**Comment by squarebracket** [comment]
```javascript
       var myCustomCallback = function(player, mediaPlayer) {
            mediaPlayer.on('qualityChangeRendered', function(event){
               // event.newQuality is the newly rendered quality
               console.log(event.newQuality);
            });
        };
        videojs.Html5DashJS.hook('beforeinitialize', myCustomCallback);
```

**Comment by Yalhu** [comment]
@squarebracket It's pretty good. Thanks. I don't neet to use `player.dash.mediaPlayer.getQualityFor('video')`(the long sting) any more.
