### ISSUE TITLE
playing the DRM protected content in Chrome with widevine token

### ISSUE THREAD

**Issue by arunvjy** [videojs/videojs-contrib-dash#215]
I am trying to play the video content that are protected by wide vine drm.

Using video js cdns are,
For Video JS:
        https://unpkg.com/video.js/dist/video.js
For dash.js:(2.6.2)
       //cdn.dashjs.org/latest/dash.all.debug.js
For video-contrib-dash:
       https://unpkg.com/videojs-contrib-dash/dist/videojs-dash.js

When I tried to play it on Chrome it throws "No Compatible Source not Found " error. But when i play the same code in Mozilla 56.0(32-bit) video plays perfectly. I am using google wide vine DRM.  I checked with the live example too. The same thing happens there also.

     I put both the code and video stream  in localhost and i played it via xampp. It plays the video perfectly.

My source: 
https://s3.ap-south-1.amazonaws.com/singam3/stream.mpd

My DRM:
https://wv.test.expressplay.com/hms/wv/rights/?ExpressPlayToken=AwAAAxENaUQAAABgkTO3e7rokJTaxCShhaWcdVwhUfS8wjc8pbmnsLE7qGfS2yMrTKBZ7qP7INeoVLOdvbcjChwkCtSkI2HUROhYyFZ_jDKTksu3RtSlzLbu4SI6UNCeRfpMZ35d_vkXw2GYqZk7yfLQ2HSWI6znNPoZK95gVmA

Any helps, It could be great for me. Thanks in advance.

**Comment by asadmalik3** [comment]
@arunvjy Have you found a solution for this?

**Comment by arunvjy** [comment]
Yes. I have solved this issue.

**Comment by asadmalik3** [comment]
How did you do it? Can you share it?

**Comment by arunvjy** [comment]
what is the issue you are facing regarding this. I can't share the entire code with you. even though it's not a big deal to play the drm in browsers.

**Comment by arunvjy** [comment]
the url should be  https:// for chrome
