### ISSUE TITLE
Unsupported IE11 Windows 10 dash profile - videojs-dash plays sound with black screen

### ISSUE THREAD

**Issue by farhumaglass** [videojs/videojs-contrib-dash#219]
Hey,

The latest Windows 10 natively supports the following standard dash profiles (can be found on this [link](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/dash-profile-support)):
```
urn:mpeg:dash:profile:isoff-live:2011
urn:mpeg:dash:profile:isoff-main:2011
```
There are certain websites, such as BBC.com, who use a different profile - which is *not* supported in Windows 10 with IE11. 
The result is a black screen video with a playing sound. 

The profile is:
```
urn:dvb:dash:profile:dvb-dash:2014
```
Link to webpage using this dash video profile:
www.bbc.com/news/world-us-canada-41559875
MPD source of the video:
http://vod-dash-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_sd/45ee36-p05jlwjh/vf_p05jlwjh_99daa933-e7e9-496d-9cbc-ab31895e5380.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1510074740_accf059b4edc7ecef1e40997fe10e014

Can the plugin call the `'error'` event, so we know we need to call our fallback logic?

Thanks guys !

**Comment by Kasher** [comment]
:+1:

**Comment by Yalhu** [comment]
I had this same case, but there is no black screen on Edge/ie11. The video can play ,but fired player error:code 4, which I listened alert a error msg. Finally , I change 'alert` to 'console'. It won't be the perfect solution. 

It should be network disconnect. On chrome error code is 2, but on Edge/ie11 error code is 4. videojs/video.js#5089

**Comment by squarebracket** [comment]
The MPD is parsed and errors are dispatched in dash.js, which this plugin wraps. We only re-throw the errors that are dispatched from dash.js as more generic errors. For that feature, you'll have to [file an issue against dash.js](https://github.com/Dash-Industry-Forum/dash.js/issues/new).
