### ISSUE TITLE
Video.js live stream setup: help request

### ISSUE THREAD

**Issue by DanielMartine** [videojs/videojs-contrib-dash#228]
Hi there, 
I'm working with mpeg dash to stream live between mp4box and dash.js. The problem arises on the client side when the user pauses for too long time the playhead tries to read a point where the buffer has already passed. I'can't find how to get a live skin without play pause or seekbar, actually i try video.js to customise the interface, i use the standard configuration, and css configuration don't give me what i need, i wish to know if there is an easy way to display live streaming with properly controls and behaviour. 
Thanks a lot,
Dan

**Comment by squarebracket** [comment]
Have you seen this happen on any browser / OS in particular? I've tried reproducing this, and I think I may have encountered this twice, but each time I try to reproduce it, it works fine.

Do you have a test stream for which this reliably happens?

What versions of videojs-contrib-dash and dash.js are you using?

For reference, here is the reproduction steps I'm trying:
1. Play a dash live stream
2. Hit pause
3. Wait long enough for the segment following the last one we downloaded to no longer be available
4. Hit play

I see it resume playback at the new live point, most of the time. Occasionally it'll start playing back the old buffer first, but I haven't been able to nail down a solid condition that causes that.

**Comment by DanielMartine** [comment]
Thanks i resolve it by adding on html the following javascript:
```
      <script>
  var player = videojs('tv-video');
  player.src({ src: 'video/manifest.mpd', type: 'application/dash+xml'});
  player.play();
      player.on("pause", function () {
        player.one("play", function () {
          player.src({"type":player.currentType(), "src":player.currentSrc()});
          player.play();
        });
      });
</script>
```

This resume always on all browsers also Android / Chrome
