### ISSUE TITLE
Struggling with Webpack + React - Please Help

### ISSUE THREAD

**Issue by iq-dot** [videojs/videojs-contrib-dash#238]
Hi All,

I have been struggling and trying for a while to get this working within Webpack as part of a React component.

I don't believe React here has any issues as the main problem seems to be that videojs-dash is not setting itself up on my videojs instance.

My versions:

"dashjs": "^2.6.6",
"video.js": "^5.20.2",
"videojs-contrib-dash": "^2.9.2",

Here are my import statements

```
import React from 'react';
import videojs from 'video.js';

import 'dashjs';
import 'videojs-overlay';
import 'videojs-playlist';
import 'videojs-contrib-dash';
import 'videojs-vast-vpaid/dist/videojs_5.vast.vpaid';

console.log('This is undefined', videojs.Html5DashJS);
```

The other videojs plugins seem to work fine but dash isn't, am I doing something wrong? I see other issues where people have done just the above and they have it working.

I tried also playing a dash video source and I get media unsupported, which means contrib dash isn't there.

If anyone sees a mistake, please let me know or what I could do to debug.

**Comment by techterbium** [comment]
Hello @iq-dot - how did you solve this problem? I am seeing this issue. any help is much appreciated.
