### ISSUE TITLE
Video/audio out of sync during play only with Safari

### ISSUE THREAD

**Issue by DanielMartine** [videojs/videojs-contrib-dash#239]
Hi there, testing a live stream with video.js contrib dash generated by MP4Box.
I can notice a problem of audio / video synchronization that occurs only after some loops of the video in input and only on Safari (with chrome there is no delay):
The problem starts to occur only when the loop begins repetitions:
For example if I watch a video of 20 minutes, audio and video are synchronized, when the video repeats its self as desired with -dash-live the delay between audio and video begins to grow, which will become evident after 3, 4 repetitions.
if I reload the page the audio will be back synchronized.
The problem is only visible after the repetition of several loops.
There are no errors from mp4box,
The test was performed with video.js contrib dash.

**TWO HOURS PER TEST ON DESKTOP:**
safari on osx positive: audio before video
chrome on osx negative test

**TWO HOURS PER TEST ON ANDROID/CHROME**
Always negative

This is the video used for test: https://www.sendspace.com/file/kj17x5

I was thinking the issue is on git gpac but when I found out the problem is only on Safari, I thought it was a player issue, some ideas?

Thanks!

**Comment by gesinger** [comment]
Hey @DanielMartine , are you still seeing this issue? If so, it may be worth opening the issue with https://github.com/Dash-Industry-Forum/dash.js , as we wrap their player for this source handler.
