### ISSUE TITLE
Using dash.js APIs in combination with video.js APIs when using videojs-contrib-dash

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#24]
Please can anyone provide some info on using dash.js APIs in combination with video.js APIs when using videojs-contrib-dash

In Particular, we'd like to use the dash.js APIs:
MediaPlayer.setMaxAllowedBitrateFor('video', 2000)   // to limit the quality when not Fullscreen
MediaPlayer.setMaxAllowedBitrateFor('video', NaN)    // to remove a cap when Fullscreen

But as far as I understand it, videojs-contrib-dash grasps control of the normal DASH context and source and passes this to video.js.  So, how would we use these DASH APIs in conjunction with video.js controlling the player?

Any example code asap would be hugely appreciated!

Thanks

Richard

**Comment by forbesjo** [comment]
We'll investigate the options we have at the moment but this may have to wait until videojs/video.js#2616 is resolved.

**Comment by richardbushell** [comment]
Hi Jo, sorry this can be closed, I got it working fine through the videojs souce handler.

**Comment by chemoish** [comment]
@richardbushell, would it be possible to post your example code? I am interested in learning, then adding some examples so its more clear on how this tech can interface with the MediaPlayer.
