### ISSUE TITLE
Send Cookies?

### ISSUE THREAD

**Issue by drsolaris** [videojs/videojs-contrib-dash#242]
Hi,

Is it possible to send cookies with every request? I was hoping to use [Cloudfront Signed Cookies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html) to protect access to my content, but can't see a way to make this happen.

Thanks!

**Comment by squarebracket** [comment]
Have you tried using [setXHRWithCredentials](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#setXHRWithCredentialsForType__anchor)?

**Comment by gesinger** [comment]
Thanks for answering @squarebracket !

**Comment by MTonomy-Nchinda-Nchinda** [comment]
As an addendum, the set of credentials I've used is ['GET', 'MPD', 'MediaSegment', 'InitializationSegment', 'IndexSegment', 'other']. Some optimization is needed, I don't think some of them like 'GET' and 'other' are necessary.
