### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by SteveYurka** [videojs/videojs-contrib-dash#245]
Hey, sorry for posting a non-issue question here, I am fairly new to Typescript, but I was wondering if there were any typing's file for this project, as I haven't been able to find any online anywhere.

Otherwise I am not sure how to access the Html5DashJS class which this library provides on top of videojs

Thanks for your time, very much appreciated

**Comment by squarebracket** [comment]
Could you elaborate what you're trying to do? There's not much reason to access `Html5DashJS` directly; configurations for dash.js should be done by [passing options to the videojs function](https://github.com/videojs/videojs-contrib-dash#passing-options-to-dashjs).

To answer your question, though -- there is no typing file.

**Comment by SteveYurka** [comment]
Thanks for your response

I have been trying to get access to the dash media player itself. Based on the video.js typings this didn't really seem like I could do this (unless I have misunderstood)

Otherwise, I was trying to use the initialisation hook since the callback returns me the dash mediaPlayer also. 

The reason I wanted to access the dash media player was to read the available bit streams (and possibly some other methods) in order to create a quality menu where you can set it to auto/1080/720/etc, depending on what is available.

For example, in the iniitalisation hook listed at the bottom of this projects readme, how is it possible to call this in typescript?

videojs.Html5DashJS.hook('beforeinitialize', myCustomCallback);

**Comment by squarebracket** [comment]
I'm afraid I'm not very familiar with typescript either, but if your compiler is complaining that `myCustomCallback` isn't typed, I _believe_ you could just define something in your types file that would declare that parameter as `any`. You might want to try googling for how to integrate a non-typed library into a typed library.

You could also try dropping by the #playback channel on [the videojs slack](http://slack.videojs.com/), someone there might be more helpful.

**Comment by SteveYurka** [comment]
Thank you very much for your help! 

I have created a custom version of the video.js types file which supports the extensions I need (eg contrib-dash, contrib-hls, etc) and have it all working now.

Just wanted to make sure I wasn't missing anything in regards to it already working before spending the time to figure out how that process works
