### ISSUE TITLE
Parsing the manifest failed

### ISSUE THREAD

**Issue by sandeep-ibs** [videojs/videojs-contrib-dash#260]
I am getting parsing the manifest failed error when trying to play encrypted content file. I just put file url in below live test page http://videojs.github.io/videojs-contrib-dash/ .
Here is my file path : http://192.168.0.91:9001/files/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzODQifQ.c0mmYVJWqFuVq_jO8l8hX2mNzCKAP-maCnS-mcB0O34Avy_WZ9ZppZloKx9TX80FlY8O6i92PPbpy0FRBZ3HtA/2322?download=false

Please suggest me!

**Comment by squarebracket** [comment]
Your URL is only available within your local network. You'll have to host it publicly if you want someone to take a look.
