### ISSUE TITLE
Sending init data for protected content

### ISSUE THREAD

**Issue by johnhenry** [videojs/videojs-contrib-dash#261]
The readme states:
```
For most protection schemes, the license server information (URL & init data) is included inside the manifest. The notable exception to this is Widevine-Modular (WV). To playback WV content, you must provide the URL to a Widevine license server proxy.
For this purpose, videojs-contrib-dash adds support for a "keySystemOptions" array to the object when using the player.src() function
```
So, we can set the URL via "serverURL" like so:

```javascript
player.src({
  src: 'http://example.com/my/manifest.mpd',
  type: 'application/dash+xml',
  keySystemOptions: [
    {
      name: 'com.widevine.alpha',
      options: {
        serverURL: <URL>
      }
    }
  ]
});
```
Is there a way to set a JSON object to be sent along as the payload to the URL?

**Comment by squarebracket** [comment]
The payload will be the `initData` of the video, as it should be. Could you elaborate on what you're trying to do?

**Comment by johnhenry** [comment]
@squarebracket thanks for the reply.

I'm working with a system designed by someone else and I'm not sure if it's standards compliant, so it's entirely possible, even likely that my assumptions are correct.

In my test working code, which does not use videojs-contrib-dash, we have a server <URL> to which we send a JSON payload via POST to retrieve a license. 

In my test code that uses video-contrib-dash, with the code mentioned in my previous comment:

```javascript
player.src({
  src: 'http://example.com/my/manifest.mpd',
  type: 'application/dash+xml',
  keySystemOptions: [
    {
      name: 'com.widevine.alpha',
      options: {
        serverURL: <URL>
      }
    }
  ]
});
```
i've noticed that the application sends an empty POST request to <URL> . I'm hoping that everything will "just work" if I can get the application to instead send the aforementioned JSON payload, causing it to return the proper license information. But again, my assumptions may be incorrect. Am I barking up the wrong tree?
Again Thanks! Any information that you can provide is helpful.

**Comment by squarebracket** [comment]
That does indeed sound non-standard; the POST data should never be empty. Are you sure your video is encrypted? Any chance you could share the MPD?

**Comment by johnhenry** [comment]
@squarebracket, I'm sure the video is encrypted, but unfortunately, I can't share the MPD. Looks like I'll have to dig deeper myself or find another method... thanks for your help!

**Comment by squarebracket** [comment]
Do you know the kind of encryption being used?

**Comment by johnhenry** [comment]
Not entirely sure about the kind, sorry.

**Comment by squarebracket** [comment]
I'd suggest talking to your DRM provider, then.

**Comment by bansalvks** [comment]
@squarebracket I am facing the same issue, the post request to serverURL has to take some data. Please help to let us know how to send the payload data (init data)
