### ISSUE TITLE
Widevine protected content

### ISSUE THREAD

**Issue by JordanChazottes** [videojs/videojs-contrib-dash#264]
I'm trying to play drm protected (widevine - EZDRM) content on my player, but got an infinite blackscreen loading on Firefox/Chrome.
Live example : https://jordan-player.kinow.video/api/drm (can be down sometimes)

This is how I initialize my player with the DRM : 
```
let src = {
        src: "my_url",
        type: "application/dash+xml",

        keySystemOptions: [
            {
                name: 'com.widevine.alpha',
                options: {
                    serverURL: 'https://widevine-dash.ezdrm.com/proxy?pX=MyCorrectKey'
                },
            },
            {
                name: 'com.microsoft.playready',
                options: {
                    serverURL: 'https://playready.ezdrm.com/cency/preauth.aspx?pX=MyCorrectKey'
                }
            }
        ],
        withCredentials: false
    };

player.src(src);
```

In my EZDRM back office I see the licenses issued each time i refresh my player,
![capture du 2018-07-11 16-40-33](https://user-images.githubusercontent.com/14850990/42579861-795c49de-8529-11e8-8c7d-fd9d2ea513ab.png) 
As you can see requests to manifest, audio and drm proxy seems ok but video never load.
No errors on console only a warning : 

> It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior

I got no problem using playready on Edge/IE, the video starts without any problem

I'm using :
video.js 7.0.5 (have already tried with 6.11)
dashjs 2.8
contrib-dash 2.9.3

Any help appreciate, thanks

**Comment by forbesjo** [comment]
Does your content play in Chrome with dash.js or shaka-player without video.js involved?

**Comment by JordanChazottes** [comment]
@forbesjo Just tested on dash.js player and got the same problem, video never starts ..

**Comment by squarebracket** [comment]
Video never starts or it's only ever a black screen?

I'd recommend checking out your DRM provider's playback restrictions settings (like HDCP) and comparing them to your setup. You can also [hook into the key status changes](http://cdn.dashjs.org/latest/jsdoc/ProtectionEvents.html#event:KEY_STATUSES_CHANGED) and use them to determine if it's [a playable key status](https://www.w3.org/TR/encrypted-media/#dom-mediakeystatus). This is what I do in my player to determine if output-restricted content is playable; I manually trigger an error if it is not, since the underlying dash.js does not.

**Comment by JordanChazottes** [comment]
@squarebracket I had a black screen that charges indefinitely, checking key status changes helped, key was "usable" during audio files requests and then "in need" during video files requests. After some tests I noticed that was a proxy issue. It works now, thanks for help !

**Comment by chovy** [comment]
how did you get it working?

**Comment by AkashYadav00** [comment]
+1 
Can you share the steps?
