### ISSUE TITLE
Player doesn't go into live mode when video is live

### ISSUE THREAD

**Issue by alexandrevicenzi** [videojs/videojs-contrib-dash#268]
If I play a video that is live, **contrib-dash** doesn't set live mode in **_videojs_**.

Live video: https://wowzaec2demo.streamlock.net/live/bigbuckbunny/manifest_mpm4sav_mvtime.mpd

This issue might be related to #35, which was supposed to fix this problem.

![screenshot from 2018-07-24 18-06-24](https://user-images.githubusercontent.com/2637672/43166297-8bc0294a-8f6c-11e8-9e04-b8d4c721418d.png)

**Comment by gkatsev** [comment]
So, what I noticed is that this mpd doesn't return `Number.MAX_VALUE` but rather `9007199254740991`, which doesn't equal `Number.MAX_VALUE`.

Why it's producing that duration, I have no idea.

**Comment by gkatsev** [comment]
looks like this is probably fixed in master and there's another pending change in #257.

**Comment by squarebracket** [comment]
Released v2.10.0 which includes those fixes. Let me know if that doesn't fix it.
