### ISSUE TITLE
Windows Builds fail

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#273]
For builds to succeed in Windows, the package.json files needs modifying for clean:build:-

From:
rm -rf dist dist-test es5 && mkdir -p dist dist-test es5

To:
rmdir /s /q dist dist-test es5 & mkdir dist dist-test es5

(I don't know if these would break a non-Windows build? If so, maybe push out a Windows alternative package.json too?)

p.s. It still shows that 2.9.1 is the Latest Release, so maybe push out an official build with each update anyway, as I assume 2.10.0 is OK?

**Comment by forbesjo** [comment]
We will look into changing our build to support the Windows shell, however you should be able to build using the Ubuntu subsystem if you're on Windows 10 or another form of Linux layer.

**Comment by richardbushell** [comment]
It still doesn't build on Windows using the latest revised script, so for simplicity any chance of publishing the final built files too with each release (as done previously) for simplicity? i.e:-
videojs-dash.js
videojs-dash.min.js

**Comment by gkatsev** [comment]
They're available in github releases (https://github.com/videojs/videojs-contrib-dash/releases/tag/v2.9.1) but you can also grab them from something like unpkg: https://unpkg.com/videojs-contrib-dash@2.10.1/dist/

**Comment by gkatsev** [comment]
actually, looks like 2.10.x isn't on github releases, but you can get it from unpkg

**Comment by richardbushell** [comment]
Thanks @gkatsev, unpkg dist is fine.
