### ISSUE TITLE
Re-load the video with contrib on ended event

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#28]
Is it possible to re-load the video when using videojs-contrib-dash on ended event?

We previously used to listen to the ended event and used video.load() to re-load the video and re-display the poster image ready for a possible replay by the user.

I tried adding the .load() method to the videojs player when using contrib, but it doesn't work anymore, e.g. myPlayer.load()

Is there a way to re-load the video when usng contrib?

Anyone got this to work, or know how to do it please?

**Comment by arpu** [comment]
how do you get this working?

**Comment by richardbushell** [comment]
See:
https://github.com/videojs/video.js/issues/2661
