### ISSUE TITLE
How to pass JSON body and headers to the license server and parse its response before sending it to the player?

### ISSUE THREAD

**Issue by bansalvks** [videojs/videojs-contrib-dash#286]
Hi Team,

I have a situation now, where I need to pass headers, keyMessage (provided by player) and JSON to license server call and it will return a JSON response then I have to parse the license key from the response and convert it to ArrayBuffer and pass to the player.

I am trying to figure out how to JSON data and parse the response. Is there any way to do that like we can pass a function that will call and return the ArrayBuffer instead of passing the license url?

Many thanks in advance,

Regards,
Vikas Bansal

**Comment by squarebracket** [comment]
You'll have to [ask this question to the dash.js people](https://github.com/Dash-Industry-Forum/dash.js/issues/new) since this is just a thin wrapper around that library. You could try asking on [their slack channel](https://dashif-slack.azurewebsites.net/).
