### ISSUE TITLE
Can we provide a callback instead of providing serverURL

### ISSUE THREAD

**Issue by bansalvks** [videojs/videojs-contrib-dash#299]
Hi Team,

I need to pass a custom body with some headers to the license server.

I am not able to active this using the **Videojs-contrib-dash** as I am not able to find a way to intercept the license call.

Please help me, Many thanks

Vikas Bansal

**Comment by squarebracket** [comment]
This is something you need to ask the dash.js folks as license requests are handled by that library, not videojs-contrib-dash.
