### ISSUE TITLE
Replay video

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#30]
We've tried everything but Replay video fails with continuous spinner most of the time.
Even with the example player if fails often when re-pressing the play button after it's ended: http://videojs.github.io/videojs-contrib-dash/
Our own tests use dash 1.5.1 + contrib 2.0.0 + vjs 5.0.2 and same thing, replay often fails with continuous spinner.
We've also tried:
player.on('ended', function () {
            player.exitFullscreen();
            player.hasStarted(false);
But again this fails sometimes and works other times.
Any idea on a fix to replay everytime reliably please?
It seems to not reset reliably.

**Comment by sprice** [comment]
In Chrome 46 on OS X pressing Play after the video ends starts the video again for me. What browser/OS are you testing on?

**Comment by richardbushell** [comment]
We've tried Chrome, IE, Firefox on WIn 7 and Win10, plus Chrome and Safari on Mac.
As I said, it does re-play sometimes and does not re-play other times. I can only assume that maybe some events get fired in a different order occasionally? On a related issue Safari has problems with seek and replay always as referenced here: https://github.com/videojs/videojs-contrib-dash/issues/22

**Comment by sprice** [comment]
Can you include a test case?

With my [updated test case](https://gist.github.com/sprice/86c598719d715328f692) I have tested repeatedly on OS X using Chrome 46, Firefox 43, and Safari 9 and I have had zero problems with seeking or replaying after completing playback.

**Comment by forbesjo** [comment]
@richardbushell are you still having this issue?
