### ISSUE TITLE
Not able to play .mpd files which are hosted on local system

### ISSUE THREAD

**Issue by hanumantha03** [videojs/videojs-contrib-dash#310]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/).
getting this error VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) The media playback was aborted because too many consecutive download errors occurred
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.make a directory into server
2.put your .mpd file in a folder
3.give the path of this file in the src option of player.

### Expected
Please describe what you expected to see.
I expected that the video would play.

### Actual
Please describe what actually happened.
The video content didn't play.

### Error output
If there are any errors at all, please include them here.
Gave me this error
## Additional Information
Please include any additional information necessary here. Including the following:
![error_video_player](https://user-images.githubusercontent.com/32599055/50686031-a9406880-1041-11e9-851a-e8063163a9ea.PNG)

#### videojs
what version of videojs does this occur with?
7.X
#### browsers
what browser are affected?
Chrome
#### OSes
what platforms (operating systems and devices) are affected?
Windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.
video-contrib-dash

**Comment by squarebracket** [comment]
Looks like your server is configured incorrectly since you're getting `net::ERR_TIMED_OUT`. Is your SSL cert configured correctly?

**Comment by squarebracket** [comment]
Confirmed working.
![screenshot from 2019-02-06 00-00-35](https://user-images.githubusercontent.com/127774/52321533-3f4e1280-29a3-11e9-96fa-78090ffa6177.png)
