### ISSUE TITLE
Is it possible to support browser < IE11 ?

### ISSUE THREAD

**Issue by yancey918** [videojs/videojs-contrib-dash#32]
Thanks for your great project.
I know dash.js just support  browser > IE11
Now I consider use HLS with flash Videojs when the browser < IE11
Is this 'videojs-contrib-dash' could support like this . How ?
Thanks

**Comment by dmlap** [comment]
It would probably require a Flash-based fallback for dash content. There are a couple projects that attempt to do this but we don't have plans to integrate any of them right now. If you're interested in contributing, though, we'd certainly love a PR that added support for older IE!
