### ISSUE TITLE
[3526][SourceBufferSink] SourceBuffer append failed "QuotaExceededError: The quota has been exceeded."

### ISSUE THREAD

**Issue by thanawatkie** [videojs/videojs-contrib-dash#320]
## Description
Briefly describe the issue.
When playback reaches some point of the video and stops playing then print error 

### Expected
Please describe what you expected to see.
I want to play the video to the end

### Actual
Please describe what actually happened.
Playback stuck at some point of video

### Error output
If there are any errors at all, please include them here.
[3526][SourceBufferSink] SourceBuffer append failed "QuotaExceededError: The quota has been exceeded."
[3528][BufferController][audio] Quota exceeded for type: audio, Critical Buffer: 554.2570664000003 Debug.js:233:25
uncaught exception: Invalid Arguments
[3936][Stream] onBufferingCompleted - can't trigger STREAM_BUFFERING_COMPLETED because streamProcessor audio is not buffering completed 
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
7.1.0

#### browsers
what browser are affected?
Safari, Chrome, Firefox

#### OSes
what platforms (operating systems and devices) are affected?
Windows, MacOS

### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-contrib-eme

**Comment by squarebracket** [comment]
This is an error with the underlying dash.js, you'll have to [file an issue against that project](https://github.com/Dash-Industry-Forum/dash.js/issues/new).

**Comment by ParasPidurkar** [comment]
@squarebracket  It is mentioned that the issue is resolved with the https://github.com/Dash-Industry-Forum/dash.js/pull/3691
as mentioned in the  https://github.com/Dash-Industry-Forum/dash.js/issues/2934.   After building the mentioned dash.js module and using it with video-contrib.js I am getting following error.

`Settings parameter streaming.fastSwitchEnabled is not supported`
