### ISSUE TITLE
Dash 3.0.0 support?

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#336]
As per the title, are there plans to support Dash 3.0.0? Are code changes required?

**Comment by gkatsev** [comment]
I haven't really been following it, so, not sure how bad it is. Maybe @squarebracket has a better idea.
I think if it's not a lot of work (or if someone wants to submit a PR) it would be nice to have a version that supported it but our focus is on our http-streaming project nowdays.

**Comment by interpegasus** [comment]
Are there any updates on this?

https://github.com/videojs/videojs-contrib-dash/pull/334

Thanks

**Comment by pukuri** [comment]
any updates?

**Comment by gkatsev** [comment]
Unfortunately, we don't have the bandwidth to work on this. Updating to 3.0 isn't a drop-in update https://travis-ci.org/github/videojs/videojs-contrib-dash/builds/661448572. If someone makes a PR to update it to 3.0 we'd be happy to review and release the update, but we don't have plans to update it ourselves right now.

**Comment by ericrav** [comment]
Wasn't this closed by https://github.com/videojs/videojs-contrib-dash/pull/349 ?
The Readme still says only 2.x is supported though

**Comment by gkatsev** [comment]
Yup, latest contrib-dash uses dash 3.x. Guess we forgot to update the readme (and this issue)
