### ISSUE TITLE
videojs didn't return any error if stream stop

### ISSUE THREAD

**Issue by yancey918** [videojs/videojs-contrib-dash#34]
If I stop the stream after playing few mins . but the videojs didn't return any error message 
How could I check if my live stream is still playing ?  Thanks
is it a bug ?

**Comment by yancey918** [comment]
Hello , any one could help ?  Thanks

![image](https://cloud.githubusercontent.com/assets/9336708/11888707/b721ff60-a57b-11e5-9dc2-fdce2c85e38b.png)

**Comment by forbesjo** [comment]
We'll look into adding better error handling for this kind of situation.

**Comment by TimIsOverpowered** [comment]
any updates on this?

**Comment by forbesjo** [comment]
This should be fixed when #141 is merged
