### ISSUE TITLE
DASH Video does not show as Live

### ISSUE THREAD

**Issue by tankerkiller125** [videojs/videojs-contrib-dash#35]
Dash video live streams do not show as live. And even attempting work around (like setting controls to off and turing on the live setting) do not work. In fact he entire data-setup attribute is ignored all together. I know that it works at first because on page load I see videojs with the settings I have in the config. But after the dash gets loaded it all gets removed.

**Comment by forbesjo** [comment]
Looks like a similar issue to https://github.com/videojs/video.js/issues/3111, we'll see if we can work around the issue in this plugin.

**Comment by zshenker** [comment]
@forbesjo Any plans to still implement this? 

It seems like at the moment the duration is coming from what dash.js is setting it to on the video element. Is the intention to override this value to Infinity in the source handler?

**Comment by forbesjo** [comment]
This fix is in 2.6.1
