### ISSUE TITLE
DRM content not playing at 720P resolution

### ISSUE THREAD

**Issue by krackjack234** [videojs/videojs-contrib-dash#359]
## Description
VideoJs contrib-dash test player is not playing higher bitrates in Chrome and Tizen browser
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the url (https://jiostreamingdash.akamaized.net/content/entry/wvdata/41/61/9921a6509d3c11eb9d701d0d3ea6acd1_voot_androidtv_standard.mpd)
2. Add the license (can be shared privately)
3. Check content playback

### Expected
1. Playack works fine in lower bitrates
2. Switch to 720p  and playback should continue

### Actual
Video playback stops if user selects  720p. Audio playback continues

### Error output
No error is seen on console

## Additional Information
Please include any additional information necessary here. Including the following:

#### browsers
Chrome browser, Samsung TV browsers

#### OSes
Tizen

### plugins
videojs contrib-dash plugin is used for DRM playback

Can you please check the manifest and let us know why video playback is stuck
What we see is 720p track has different KID than other tracks. However same is playing fine with shaka player on TV

Is this because of multi drm key and because 720p has L1 widevine license?
If yes then how can we enable this with contrib-dash?

We can share the actual drm license privately via a private email.

**Comment by gkatsev** [comment]
Are you able to play back the 720p on the dash.js test page? https://reference.dashif.org/dash.js/v3.2.2/samples/dash-if-reference-player/index.html
Generally, with contrib-dash we don't have any playback and it's an issue with dash.js.

**Comment by krackjack234** [comment]
hi @gkatsev  we upgraded the videojs library and https://github.com/videojs/http-streaming library and now its working fine
