### ISSUE TITLE
Latest production release of videojs-contrib-dash

### ISSUE THREAD

**Issue by krackjack234** [videojs/videojs-contrib-dash#366]
## Description
What is the latest production release for videojs-contrib-dash (https://github.com/videojs/videojs-contrib-dash/releases)

Is it v2.10.0 (8_mar-2019 !!) or v5.0.0 tag (25 Jun 2021)?

Kindly let us know

**Comment by gkatsev** [comment]
5.0.0 is the latest. We have not gone a good job at updating the github releases. We consider the npm tags to be the canonical source of truth for the releases. https://www.npmjs.com/package/videojs-contrib-dash

**Comment by krackjack234** [comment]
Thanks
