### ISSUE TITLE
CloudFront signature

### ISSUE THREAD

**Issue by azizantoun** [videojs/videojs-contrib-dash#37]
Is there any way we can pass cloudfront directory signature to videoJS ?
/folder/file.mpd
/folder/segments/file.mp4
My signature is on the folder level I just need to pass it to the VideoJS.

Example URL:

https://dqa1slkm3n32i.cloudfront.net/output/50505_8a057bc4c7cceb4b5015cc0233699c86/50505.mpd

---Signature--
Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kcWExc2xrbTNuMzJpLmNsb3VkZnJvbnQubmV0L291dHB1dC81MDUwNV84YTA1N2JjNGM3Y2NlYjRiNTAxNWNjMDIzMzY5OWM4Ni8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDUyNjgxOTAxfX19XX0_&Signature=FwMRzQlW1tgycmgGFiFfDTPKDlsozy2IDG3JsAysbxkr~mkzurb8uP-OjBOPvEGblf1InDwsKc6-fwZUYc9MMtp~A-u3BqZ19tbGHfOxw7TUVuTOw35UGso8xtdclpj3fSSduY7aB3TMDiUSMwRDHNE2iEEbP5MowjmyR-Yd54V8J1poWTqa0y5fn6Z5KrItoihj~Mgln~tMxMD~gPRgkgrFw13zLAdDk-N-N8zgIyweUGaZ4O70bKFaulYyBlil0omxJ34CJ4LwfNJr1e4mSs3XaOQhmiC6SOj9ckGx-62BR6JFhou0UJyjF7pbcvtxVOY65Wps3ZOblssYEaTo6w__&Key-Pair-Id=APKAIXEL5M5KRSFNCUNA
---

**Comment by forbesjo** [comment]
Not sure how the Cloudfront signature works but it seems like you should be able to add it as a query parameter to the mpd url.
