### ISSUE TITLE
resolution selector

### ISSUE THREAD

**Issue by StaymanHou** [videojs/videojs-contrib-dash#39]
wonder whether there will be a resolution selector in the UI where user can select the resolution.
something like this - https://github.com/dominic-p/videojs-resolution-selector

**Comment by rodincave** [comment]
Hi!

We just did a brand new clean plugin for videojs 5+ just for this, would be happy to have some feedbacks on it:
https://github.com/streamroot/videojs-quality-picker

It works today with our integration of hls.js provider (https://github.com/streamroot/videojs-hls.js), but can easily be integrated with video.js+dash.js too. The only catch today is taht the plugin need to be initialized in the Source Handler.

**Comment by forbesjo** [comment]
#54 should add this functionality.

**Comment by forbesjo** [comment]
#66 will actually implement this feature, closing.

**Comment by StaymanHou** [comment]
:+1:
