### ISSUE TITLE
Version 2.x vs 1.x

### ISSUE THREAD

**Issue by thomaspeeters** [videojs/videojs-contrib-dash#42]
Looking at the releases, I noticed a v2.0.0 and a more recent v1.1.2. What is the difference between the two? Is v2.0.0 for use with the newly released dash.js 2.0.0?

**Comment by forbesjo** [comment]
v2.0.0 of this project is for use with video.js 5.0 and is not related to the dash.js version.

**Comment by thomaspeeters** [comment]
Oh OK. So there is only one current release compatible with Video.js 5.x. That's good to know.

Is the development of this project closely tied with the dash.js project? I saw a version of this project is included in the dash.js project, but it's outdated and incompatible with Video.js 5.x. Is there a reason for this? Or are the two projects totally out of sync at the moment?

**Comment by forbesjo** [comment]
The dash.js copy of this plugin is very old (1.1.0 from July). This repo should be the destination for the latest code. 

@imbcmdth should we keep the dash.js copy of this plugin up to date with this project or just have the readme direct users here?

**Comment by forbesjo** [comment]
I'll open a PR against dash.js and update the plugin found there.

**Comment by forbesjo** [comment]
I'll close this when it's merged into dash.js.

**Comment by forbesjo** [comment]
See https://github.com/Dash-Industry-Forum/dash.js/pull/1378

**Comment by forbesjo** [comment]
The plugin code has been updated in dash.js, closing.
