### ISSUE TITLE
Dash is not defined error with dash-2.0.0

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/videojs-contrib-dash#45]
I have downloaded dash-2.0.0 and include in script with dash.all.min.js i got thi error.

Uncaught ReferenceError: Dash is not defined
Html5DashJS @ videojs-dash.js:72
videojs.getComponent.registerSourceHandler.handleSource @ videojs-dash.js:220
_Tech.setSource @ tech.js:719
techCall_ @ player.js:1195
(anonymous function) @ player.js:1881
ready @ component.js:815
src @ player.js:1875
(anonymous function) @ index.html?editors=1000:28(anonymous function) @ index.html?editors=1000:33

**Comment by nickygerritsen** [comment]
Dash.js changed quite a bit in 2.0.0.

We are working on integrating it in PR #38

**Comment by gkatsev** [comment]
Thanks @nickygerritsen.
Going to close this. Please follow #38 for progress.
