### ISSUE TITLE
How can i use videojs-dash with dash-2.0.0 ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/videojs-contrib-dash#47]
i want to update myself day by day for better performance with less bug and tell me how i can use with dash-2.0.0 or when you people are going to update the latest version to use with dash-2.0.0 ?

**Comment by forbesjo** [comment]
Once #49 is merged in this plugin will be compatible with dash.js 2.0

**Comment by forbesjo** [comment]
The latest version of this plugin is now compatible with dash.js 2.0. Closing this ticket.
