### ISSUE TITLE
Vast is not working with dash .

### ISSUE THREAD

**Issue by baqarrivi** [videojs/videojs-contrib-dash#50]
1) I am using version v2.0.0 of dash.
2) video.js version is 5.8.0
3) plugin url is this .http://mailonline.github.io/videojs-vast-vpaid/index_5.html#

**Comment by whatvn** [comment]
what "is not working" means?

**Comment by baqarrivi** [comment]
Vast is not working with dash

**Comment by whatvn** [comment]
what is the error? my experience when working with mailonline's vast plugin is that plugin is relied on some videojs internal events, maybe witth videojs-dashjs plugin, these events were not fired properly, so ads content cannot started.

**Comment by forbesjo** [comment]
Can you provide a reduced test case?

**Comment by forbesjo** [comment]
Closing because there hasn't been an update in a little while, please reopen if this is still an issue. Thank you.
