### ISSUE TITLE
Dash.js integration

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#58]
Is/Will there be any documentation on how to integrate with Dash.js/API?

I am currently leveraging `Html5DashJS.useVideoJSDebug` (https://github.com/videojs/videojs-contrib-dash/blob/master/src/js/videojs-dash.js#L74)

Are there other integration points within the tech?

---

Here is my current implementation to disable logging.

```js
import 'dashjs';
import 'video.js';
import 'videojs-contrib-dash/dist/videojs-dash.js';

videojs.Html5DashJS.useVideoJSDebug = function (player) {
  // https://github.com/Dash-Industry-Forum/dash.js/blob/development/samples/getting-started-basic-embed/listening-to-events.html#L17
  player.getDebug().setLogToBrowserConsole(false);
};
```

Knowing that there is a open ES6 PR, are there plans to handle this differently?

**Comment by chemoish** [comment]
Somewhat seemingly related to https://github.com/videojs/videojs-contrib-dash/pull/38#issuecomment-184614755.

**Comment by forbesjo** [comment]
I think we should have a sourceHandler option for logging and other setup options (see https://github.com/videojs/video.js/issues/2616). We still need to figure out a way to exposure the active sourceHandler through the player.

**Comment by chemoish** [comment]
@forbesjo secondarily, would it be possible to add separate examples for browserify and webpack?

Not sure if you would rather it be baked into grunt or have separate `example/` folder.

My current webpack implementation can be setup to work with v2.1.0 OR the browserify version.

(my repo is going to break as soon as master gets released)

**Comment by gkatsev** [comment]
We just need to update our build scripts and remove browserify shim from dependencies and from the browserify config in the package.json and only use it when building the dist file.

**Comment by forbesjo** [comment]
@chemoish I will open a PR for contrib-dash similar to https://github.com/brightcove/videojs-playlist/pull/44

**Comment by forbesjo** [comment]
@chemoish a new version of this plugin has been released with the browserify changes, does this help with your development workflow?

**Comment by chemoish** [comment]
I am going to be out for a few days, but I'll check Monday. Thanks!

Also, would you be against me adding something similar to…

https://github.com/Dash-Industry-Forum/dash.js/tree/development/samples/modules/webpack?

**Comment by chemoish** [comment]
@forbesjo Thanks.

```javascript
-import 'dashjs';
-import 'expose?videojs!video.js';
 import 'video.js/dist/video-js.css';
 import 'videojs-contrib-dash';
+import videojs from 'video.js';

window.videojs = videojs;
```

**Comment by pebanfield** [comment]
Has this issue been closed because it is resolved? The above configuration is not working for me. Is there an example project somewhere that I could have a look at? thanks
