### ISSUE TITLE
Dash and HLS

### ISSUE THREAD

**Issue by Tralapo** [videojs/videojs-contrib-dash#6]
Because of the recent bad news about Flash (Firefox is even blocking the most recent version!), I started to investigate how I could distribute my livestreams different.

At the moment, I serve a rtmps stream for desktops (so, Flash) with HLS on Android/iOS with the standard Video.JS. Now I was trying to get MPEG-DASH to work, because of the lack of support for HLS in desktopbrowsers.

I can get the DASH stream to work in Chrome and IE, but not in Firefox. Is this correct? DASH doesn't work on my Android device, so I added the HLS source too. But the player doesn't serve the right one automaticly, with as result my stream no longer works on Android, because it tries to serve DASH.

I then tried to switch the sources, HLS first and DASH as second. Then Android works again, and all desktop browsers are broken.

Is it possible to serve DASH to desktopbrowsers and HLS to iOS/Android, so you can stream completely without Flash? I'm starting to doubt it.....

**Comment by mmcc** [comment]
> Because of the recent *bad* news

Despite dreading dealing with issues this is going to cause us, I'm still totally on board with Firefox here. Gotta look on the bright side of things! I realize this is also not a wonderful user experience, but can't users still view the content by clicking to enable Flash?

> I can get the DASH stream to work in Chrome and IE, but not in Firefox. Is this correct?

Unfortunately yes, this is correct. In the stable version of FF, MSE is only available behind a feature flag. FF Developer Edition supports MSE by default now, so MSE should be available in the stable branch shortly, but we're not there yet.

> I then tried to switch the sources, HLS first and DASH as second. Then Android works again, and all desktop browsers are broken.

That seems weird to me. Can you put up an example so we can try and take a look?

**Comment by Tralapo** [comment]
Thanks for the answer. I created a testpage for you to look at. It contains three players:

1) My current setup. RTMPS in Flash on desktops, HLS on iOS/Androids. Works fine, but I would like to drop Flash.

2) MPEG-DASH and HLS. As said it works in Chrome/IE. On Android, DASH is selected and doesn't work. It does not switch to HLS.

3) HLS and DASH. Works as expected on Androud, but now the desktop browsers also choose HLS and playback fails. Dash isn't selected.

[See for yourself here](http://bit.ly/1MwXNTq)

**Comment by imbcmdth** [comment]
@Tralapo Glad it worked out for you! :+1: 

Closing as fixed.
