### ISSUE TITLE
Release browserify support?

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#62]
Are you guys planning on releasing https://github.com/videojs/videojs-contrib-dash/commit/e8ce7716ccd4c00eec6ee933f00038640d53a3f7 anytime soon?

**Comment by chemoish** [comment]
Related to https://github.com/videojs/videojs-contrib-dash/issues/58#issuecomment-204612163

**Comment by forbesjo** [comment]
We will be doing another release with the browserify changes and #54 once it's merged.
