### ISSUE TITLE
Upgrade `MediaPlayer.create` to conform with dash#~2.0.0

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#64]
SEE: https://github.com/Dash-Industry-Forum/dash.js/issues/1317#issuecomment-207627034

**Comment by up4** [comment]
Reading the open PRs and issues, it is difficult to understand where is the Dash.js 2.x support for this project headed ? What needs to be done ? How can one help ? Thanks !

**Comment by chemoish** [comment]
Dash 2.x works as it stands from the initial upgrade in https://github.com/videojs/videojs-contrib-dash/commit/3e7258e88e8a65855263548607cfb28a9e4378ed (single and common manifests).

However, I have had playback issues if the license server 500's on key exchange. If that issue occurs, you can no longer use the player until you refresh the page (probably something to do with disposing).

One of the dash members recommended fixing how dash is disposed (only create once instead of recreating every time). This may or may not solve the issue...

---

Once I get back to player work I will address this issue. Feel free to open PR.

As for the support, I am not sure I haven't spoken to @forbesjo.

**Comment by up4** [comment]
ok thanks for the update

**Comment by chemoish** [comment]
videojs-contrib-dash implementation doesn't seem to have an effect on the outstanding 500 license issue. The dash player dispose issue probably should be considered before closing this issue.

Regarding the 500 uncaught exception plaguing both video.js and dash.js I opened up another issue with them.

**Comment by forbesjo** [comment]
@chemoish I believe #79 should fix this

**Comment by chemoish** [comment]
:tada: thanks.
