### ISSUE TITLE
Firefox video not playing most of the time

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/videojs-contrib-dash#65]
my video is not playing in firefox browsers most of the time..

Firefox Version: 45.0.2
Videojs Version: 5.8.8
Dash Version: 2.0.0
Dash-contrib Version: 2.1.0

here is the link which is not working in firefox http://bestsongs.pk/videos/dear-dad-trailer-2016/

**Comment by forbesjo** [comment]
Is it still an issue with the latest version of dash.js (2.1.0)?

**Comment by ZohaibGhafoor** [comment]
yes i allready checked with 2.1.0 same issue.

**Comment by arpu** [comment]
https://github.com/Dash-Industry-Forum/dash.js/issues/1349

**Comment by baqarrivi** [comment]
I am having Same problem & mostly it drops my video in chrome as well ,
i am using videojs 5.9.1
and videojs-vast-vpaid
Dash Version: 2.0.0
Dash-contrib Version: 2.1.0

Here is my link.
https://bestsongs.pk/videos/kaabil-trailer-2017/

& its also not working on google chrome canary

**Comment by forbesjo** [comment]
I believe this is fixed because of the last comment in https://github.com/Dash-Industry-Forum/dash.js/issues/1349, if this is still an issue please update.
