### ISSUE TITLE
Clear console log

### ISSUE THREAD

**Issue by AdielMtz** [videojs/videojs-contrib-dash#68]
How can I clear all the messages in the console log?

**Comment by chemoish** [comment]
Picture?

**Comment by AdielMtz** [comment]
![all](https://cloud.githubusercontent.com/assets/18149652/14939258/ad555c14-0f04-11e6-87ac-48db324e07a7.png)

**Comment by chemoish** [comment]
https://github.com/videojs/videojs-contrib-dash/issues/58

**Comment by forbesjo** [comment]
As chemoish linked you can turn off dash.js's logging with: 
```javascript
videojs.Html5DashJS.useVideoJSDebug = function (player) {
  player.getDebug().setLogToBrowserConsole(false);
};
```

**Comment by ehoch** [comment]
I have attempted to turn off dash's logging using this and the latest code:

```
videojs.Html5DashJS.beforeInitialize = function(player, mediaPlayer) {
  // Log MediaPlayer messages through video.js
  if (videojs && videojs.log) {
    mediaPlayer.getDebug().setLogToBrowserConsole(false);
    mediaPlayer.on('log', function(event) {
      videojs.log(event.message);
    });
  }
};
```

However, it's still flooding my console. I run the latest version of videojs-contrib-dash and 2.3.0 of dash. Any ideas @chemoish? Thanks!

**Comment by forbesjo** [comment]
```
 mediaPlayer.on('log', function(event) {
      videojs.log(event.message);
 });
```

This will use video.js's logging system and will still flood your console.

**Comment by ehoch** [comment]
Thanks @forbesjo. I actually just copied and pasted the code from the home page in this issue, but when I attempted to test I removed that. I went with was:

```
  videojs.Html5DashJS.beforeInitialize = function(player, mediaPlayer) {
    mediaPlayer.getDebug().setLogToBrowserConsole(false);
  };
```
I can verify that the code is being called and mediaPlayer.on('log') did in fact also log entries. But nothing I do is removing the flood from dash.

**Comment by ehoch** [comment]
@forbesjo Any additional help here? Sorry to bug you, but it's still flooding on console no matter what code I use. I updated the latest version and tried the new hooks and same thing:

```
    videojs.Html5DashJS.hook('beforeinitialize', function(player, mediaPlayer) {
      mediaPlayer.getDebug().setLogToBrowserConsole(false);
    });
```

**Comment by chemoish** [comment]
@ehoch one possibility is that you are not using the same `videojs` instance and could be attaching to the wrong one? which would mean the code would be called, but it would be a different instance than you are using in the browser.

other than that, i can't think of anything else. 🤔

**Comment by aungsitnaing** [comment]
Try this code to disable console log.

```javascript
var player = videojs('my-player', config, function() {
  try {
    this.dash.mediaPlayer.getDebug().setLogToBrowserConsole(false);
  } catch (error) {
    console.log(error);
  }
});
```

**Comment by yonbeastie** [comment]
@aungsitnaing I gave your suggestion a try but wasn't able to get it working until I put the try/catch in a `setTimeout`. It seems that `player.dash` is not available at the time that the `player.ready` callback is triggered.
