### ISSUE TITLE
.MPD Resolution Tool Auto to all resolution 

### ISSUE THREAD

**Issue by baqarrivi** [videojs/videojs-contrib-dash#69]
I have seen in MPD players it has resolution tool inside it but i am having a confusion why contrib dash don't has it Eg 

![screenshot-vjs5](https://cloud.githubusercontent.com/assets/15075559/14784996/d3d2274c-0b11-11e6-80a1-1a823734d564.png)

**Comment by forbesjo** [comment]
We will be exposing an API for this with #66 and video.js may have a generic renditions API in the future to group this project's rendition selection API and the contrib-HLS rendition selection API (not yet implemented). That generic API will probably have a menu similar to the one you posted like we do for textTracks and audioTracks.

**Comment by forbesjo** [comment]
We have decided to go another route and so there will not be any more development against that PR. When dash.js exposes this functionality we will use their API in this plugin.
