### ISSUE TITLE
VOD DASH streaming with nginx?

### ISSUE THREAD

**Issue by HankBrown** [videojs/videojs-contrib-dash#71]
Using https://github.com/arut/nginx-rtmp-module
Got this working with videojs:
`src="rtmp://mysite.com/vod/&mp4:52725.mp4?foo=fie" type="rtmp/mp4"` 
Nginx streams the mp4, and my php script gets the on_play notification to validate foo=fie
Perfect!

Now failing to stream dash like so:
`rtmp://mysite.com/vodash/&mp4:19577.mpd?foo=fiddle" type="rtmp/mp4" `

I begin to wonder if I am throwing stones at the sky. Is this even possible?
Can nginx stream DASH VOD?

Works (mp4 no dash)
```
	application vod {
		play /home/mysite/content/mp4;
		on_play http://mysite.com/onplay.php;
	}
```
Thought I would be able to add "dash on;" to the config, change the application name to vodash and be happy.

Apologies for posting a related issue, not specifically tied to the project.
Not finding help elsewhere yet, hoping a soul here will recognize my problem.

**Comment by forbesjo** [comment]
Is this still an issue? If so could you provide a sample player that points to your setup?

**Comment by HankBrown** [comment]
Nope. That was almost three weeks ago and I moved on. Now serving HLS instead.

Thank you for the reply. I take it to mean the src line and nginx app are as posted are syntactically correct. Will pick up DASH again when time permits, and be sure to shelve the situation properly for a delayed post mortem. Thanks again for your time.
