### ISSUE TITLE
Add webpack integration example

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#80]
Worth creating something similar to https://github.com/Dash-Industry-Forum/dash.js/tree/development/samples/modules/webpack?

Too much maintenance?

Looks like `Dash.js` leverages grunt and browserify as their root.

**Comment by gkatsev** [comment]
I don't think it should be necessary. At least nothing webpack specific.
Both webpack and browserify should be able to use it some like this:
```js
import video.js from 'video.js';
import 'videojs-contrib-dash';
```

**Comment by gkatsev** [comment]
I have an advanced player example on the videojs website, I could potentially add contrib-dash to it as well. (https://github.com/videojs/videojs.com/pull/51/files#diff-03294417c3330c12bcd42b405d1b1af6R4)

**Comment by chemoish** [comment]
Ok sounds good. I'll deal for now.

Trying to debug issues I find and I have to `npm link` quite frequently.

- repo (complex SSR webpack)
- player (non-trivial player webpack, trivial example webpack)
- videojs-contrib-dash
- dashjs

**Comment by gkatsev** [comment]
Oh, yeah, linking so many things together can get tricky. Let us know if you need help with that.
