### ISSUE TITLE
Stream doesn't start when ad finishes

### ISSUE THREAD

**Issue by Palethorn** [videojs/videojs-contrib-dash#82]
I'm not sure where to report this issue. I'm currently testing videojs-dash plugin for videojs with vast-vpaid plugin https://github.com/MailOnline/videojs-vast-vpaid. There is an issue of a stream not starting after the ad finishes. There is a configured live example with debug versions of plugins here http://player.cavar.pw/videojs-vast/

Example code used for embedding:
```javascript
var setup = {
    'techOrder' : ['html5'],
    'controls' : false,
    'preload' : 'auto',
    'autoplay' : true,
};

window.player = videojs('video-js', setup, function() {
    this.vastClient({
        adTagUrl: 'https://hr.adocean.pl/ad.xml?id=freWvTXJkuOn6vrKYuPyUkapzdpV5yco97oIDkMlvOn.y7/aocodetype=1',
        playAdAlways: true
    });

    this.src({
        type : 'application/dash+xml',
        src: "http://coder01.spectar.tv:1935/live/_definst_/colorbars/manifest.mpd",
    });
});

document.querySelector("#button").addEventListener('click', function(e) {
    window.player.src({
        type : 'application/dash+xml',
        src: "http://coder01.spectar.tv:1935/live/_definst_/colorbars1/manifest.mpd",
    });
});
```
I have noticed the player starts buffering the stream before the ad starts, and after that it cannot resume.

**Comment by forbesjo** [comment]
Closing as this is most likely an issue with videojs-vast-vpaid. If it turns out not to be the case then feel free to reopen this.

**Comment by Palethorn** [comment]
Ok, I'm still waiting the response from other ticket. Thanks.

**Comment by fikiland** [comment]
i face the same problem too
please add option 
options = {controls: true,autoplay: true,"preload": "auto",liveui: true};
and then it solve, but at several browser you need to allowed auto play
+1:
