### ISSUE TITLE
Is it possible to provide pre-built dist files in repo?

### ISSUE THREAD

**Issue by PeterDaveHello** [videojs/videojs-contrib-dash#84]
Hi there,
I'm wondering if you can provide pre-built dist files in repo? Just for the release git tags, so that we can host this lib on cdnjs, and it's good to have an official build for users, thanks.

**Comment by PeterDaveHello** [comment]
It'll be great if you can also provide pre-built files for videojs-contrib-ads repo, thanks.

**Comment by forbesjo** [comment]
I have added the build files to the latest release tag. @incompl could you add the build files to contrib-ads when you get a chance?

**Comment by gkatsev** [comment]
@PeterDaveHello does it need to be in the tag or would having it be in github releases be sufficient?

**Comment by incompl** [comment]
I probably won't be able to get around to this for awhile, if someone else wants to do it.

**Comment by PeterDaveHello** [comment]
Hi all, thanks for your comments, the pre-built files need to be in the tagged commits only, so that cdnjs auto updater can recognize and update the new versions automatically, thanks!

**Comment by PeterDaveHello** [comment]
@forbesjo I only see the files in the latest release, but not in the tagged commit, is it possible to be in the tagged commit?

**Comment by forbesjo** [comment]
Would it be possible for cdnjs to pickup the npm package for this repo and videojs-contrib-ads? It seems like that's how videojs-contrib-hls is set up https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/videojs-contrib-hls/package.json

**Comment by PeterDaveHello** [comment]
Yes we can pickup npm packages if there are distribution purpose files.

**Comment by gkatsev** [comment]
Most of the videojs related projects publish to npm with the distribution files showing up in `dist/`. Picking the files up from npm would be our preferred method as well.

**Comment by PeterDaveHello** [comment]
Since there is no npm package info in the homepage and readme, so I actually don't know that, is there a list of the videojs related npm packages?

**Comment by gkatsev** [comment]
There's https://www.npmjs.com/package/videojs-contrib-dash, https://www.npmjs.com/package/videojs-contrib-ads, https://www.npmjs.com/package/videojs-contrib-hls, and https://www.npmjs.com/package/videojs-swf

**Comment by PeterDaveHello** [comment]
Thanks @gkatsev, I'll take a look at these packages.
