### ISSUE TITLE
Multiple sources?

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#88]
I wanted to initiate a discussion for handling multiple sources (And if its even feasible).

```
   * **Array of Source Objects:* * To provide multiple versions of the source so
   * that it can be played using HTML5 across browsers you can use an array of
   * source objects. Video.js will detect which version is supported and load that
   * file.
```

As specified by https://github.com/videojs/video.js/blob/master/src/js/player.js#L1859.

---

It doesn't seem that the `candHandleSource`, specified in https://github.com/videojs/videojs-contrib-dash/blob/master/src/js/videojs-dash.js#L112, is very robust (I am not very familiar with `SourceHandlers`).

However, understandably a majority of the _detect_ is specified by the `!!window.MediaSource`.

---

Current use case is for _protected_ content:
1. Pass in 2 sources, the first being for IE and the second being for Chrome
2. Expect IE to fail on Chrome
3. Expect retry? and Chrome to work

(There are limitations with `dash.js` and multiple sources—hence the conversation)

**Comment by dmlap** [comment]
Hey @chemoish-- can you elaborate on what sort of sources you're providing? Is the problem that you have Widevine and PlayReady encryption? If that's the case, I'd recommend taking advantage of common encryption (CENC) to express both in the same MPD. There are a couple [basic examples](http://docs.unified-streaming.com/documentation/drm/mpeg-dash.html) on Unified Streaming's site.

If you're running into some more exotic incompatibility, can you provide more details on how you're generating your streams?

**Comment by chemoish** [comment]
@dmlap, right now the only 2 sources I am providing are `playready` and `widevine` protected manifests (we currently are migrating toward CENC).

In either case, I don't believe `videojs-contrib-dash` hooks into the event system for `dash.js`—in the event of a key system failure, missing license url, etc (seems like it should?).

So, I created this issue to eventually get that far… 

Because whether the manifests are separate or combined, I would like to ideally throw in `fairplay`, `playready`, and `widevine` together and it cycle through sources/errors appropriately.

**Comment by chemoish** [comment]
@dmlap I guess, in part, this issue is outstanding in the main repo?  https://github.com/videojs/video.js/issues/1316

And currently, if `dash.js` fails, the errors are never caught. Should this be the responsibility of the tech or the tech consumer?

```js
// or something similar?
videojs.Html5DashJS.beforeInitialize = function (player, mediaPlayer) {
  mediaPlayer.on(dashjs.MediaPlayer.events['PLAYBACK_ERROR'], function (event) {
    player.error({
      code: 0,
      message: event.event,
    })
  });

  mediaPlayer.on(dashjs.MediaPlayer.events['ERROR'], function (event) {
    player.error({
      code: 0,
      message: event.event,
    })
  });
};
```

…On the other hand, it seems like that error handling and fallback logic might conflict with each other…

Thoughts?

**Comment by forbesjo** [comment]
I think for your specific situation you should probably have some logic to detect if the browser can play that protected source rather than relying on a falling back on an error. 

For the error fallback system I don't think it would conflict with error reporting since we can clear the error when the fallback is engaged.

**Comment by chemoish** [comment]
For the protected sources that sounds about right and what I expect to do until some magical solution comes forth.

Since DRM content can fail for so many reasons, should the code above be the responsibility of the consuming developer?

Or should the tech read the `event.event` and handle this messaging? Maybe leverage some existing https://github.com/videojs/video.js/blob/master/src/js/media-error.js?

**Comment by forbesjo** [comment]
I think this kind of feature should be in video.js and not implemented here as this would be duplicated in other projects like contrib-hls.

**Comment by chemoish** [comment]
Not a big deal to me, but I seems like it should be here because this is where the interaction with dash.js happens. 

The eventual API integration, whatever happens with that, and dash.js error handling should also be here..

Thanks.

**Comment by forbesjo** [comment]
Re-opening this, I would like to test the keysystems in canHandleSource

**Comment by forbesjo** [comment]
The dashjs player errors bubbling up to video.js should be resolved with https://github.com/videojs/videojs-contrib-dash/pull/141. The try-next-source feature should be handled by video.js https://github.com/videojs/video.js/issues/1316 since it would be a useful feature for other playback types.
