### ISSUE TITLE
VideoJS wants Sources, DashJS wants NO Sources

### ISSUE THREAD

**Issue by richardbushell** [videojs/videojs-contrib-dash#91]
We have an issue with the loadstart event firing twice.
VideoJS wants expressly stated Sources within the Video tag, DashJS wants NO Sources and wants to add the Source programmatically.
Bottom line is that double loadstart events are triggered, meaning that VJS 5.10.2+ fails.
See:
https://github.com/videojs/video.js/issues/3428
Could videojs-contrib-dash make them play together nicely? Or should VideoJS add programmatic source option?
Any ideas please?

**Comment by forbesjo** [comment]
We can investigate and see if there's a way to disable this behavior in dashjs. If possible you can leave the video element without source elements and change the source with `player.src({src: ..., type: ...})` (see https://github.com/videojs/videojs-contrib-dash/blob/master/example.html#L42) as a workaround.

**Comment by richardbushell** [comment]
Thanks, will try programmatically adding the source. In the meantime, I did pinpoint the break point. (from VJS issue post):
VJS 5.9.2 is OK. VJS 5.10.1 breaks.
Culprit is definitely VJS: #3285
Result is that some browsers now no longer select and play the dash source and now revert to fallback mp4 playback. Chrome & Edge still play dash, BUT Firefox and IE now revert to MP4 fallback.

**Comment by richardbushell** [comment]
Thanks Jo, yes programmatic sources solved the problem. Currently I believe that anyone using html source tags will now break dash handling if using VJS 5.10.1+ due to: videojs/video.js#3285
I will close this here as it is best fixed through a VJS issue, not contrib.
