### ISSUE TITLE
Best Way To Enable HTML Subtitles?

### ISSUE THREAD

**Issue by Petercopter** [videojs/videojs-contrib-dash#98]
What's the best way to replicate this with Video.js?

```
var url = "http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-snake.mpd";
var player = dashjs.MediaPlayer().create();
player.initialize(document.querySelector("#playerjs"), url, true);
ttmlDiv = document.querySelector("#video-caption");
player.attachTTMLRenderingDiv(ttmlDiv);
```

This is how the Dash.js player is implementing the HTML subtitle display, as seen in their demo:
http://dashif.org/reference/players/javascript/v2.2.0/samples/dash-if-reference-player/

Otherwise it's just the fallback display, without style.. The HTML subtitles use styling and position.

**Comment by forbesjo** [comment]
Caption support is currently in progress
